using System;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;
using Xunit;

namespace DbChange.Budgets.Tests;

/// <summary>
/// The inventory is data: every markdown file outside archive/, and every file in ci/, is a row of
/// ci/docs.manifest.json saying who reads it and when; every row names a file that exists; a generated file opens
/// with the banner naming its generator and a hand-written one does not; a hand-written file holds its budget.
/// </summary>
public sealed class Manifest
{
    /// <summary>The one-line banner every generated file opens with (V3_INSTRUCTION_ARCHITECTURE.md §6.10).</summary>
    internal static readonly Regex Banner = new("^<!-- generated .+ do not edit -->$", RegexOptions.CultureInvariant);

    [Fact]
    [Trait("Category", "fast")]
    [Trait("Value", "L4")]
    [Trait("Value", "A4")]
    [Trait("Value", "A10")]
    public void Every_markdown_file_outside_the_archive_and_every_ci_file_is_a_row()
    {
        var rows = Documents.Rows.Select(r => r.Path).ToHashSet(StringComparer.Ordinal);
        var missing = Repository.Files
            .Where(f => (f.EndsWith(".md", StringComparison.Ordinal) && !f.StartsWith("archive/", StringComparison.Ordinal)) || f.StartsWith("ci/", StringComparison.Ordinal))
            .Where(f => !rows.Contains(f))
            .Select(f => "docs.manifest.json: add {path, kind, owner, reader, moment, budget, generator} for " + f);

        Assert.Empty(missing);
    }

    [Fact]
    [Trait("Category", "fast")]
    [Trait("Value", "L4")]
    [Trait("Value", "A10")]
    public void Every_row_names_a_file_that_exists_and_says_who_reads_it_and_when()
    {
        var wrong = Documents.Rows.Where(r => !Repository.Files.Contains(r.Path)
                || r.Kind is not ("hand" or "generated")
                || r.Owner is not ("tool" or "ssdt" or "vendored")
                || r.Reader.Length == 0
                || r.Moment.Length == 0
                || (r.Kind == "generated") != (r.Generator is not null)
                || (r.Budget is null && r.Kind == "hand" && r.Path != "DECISIONS.md" && !r.Path.StartsWith("ci/", StringComparison.Ordinal)))
            .Select(r => "docs.manifest.json: the row for " + r.Path + " needs a file that exists, a kind, an owner, a reader, a moment, and a budget or a generator");

        Assert.Empty(wrong);
        Assert.Equal(Documents.Rows.Count, Documents.Rows.Select(r => r.Path).Distinct(StringComparer.Ordinal).Count());
        Assert.All(Documents.RootDesign, d => Assert.Contains(Documents.Rows, r => r.Path == d));
    }

    [Fact]
    [Trait("Category", "fast")]
    public void A_generated_file_opens_with_the_banner_and_a_hand_written_file_does_not()
    {
        var wrong = Documents.Rows
            .Where(r => r.Path.EndsWith(".md", StringComparison.Ordinal))
            .Where(r => Banner.IsMatch(Repository.Lines(r.Path).FirstOrDefault() ?? "") != (r.Kind == "generated"))
            .Select(r => r.Path + (r.Kind == "generated" ? ": generated, so its first line is the banner <!-- generated by … do not edit -->" : ": hand-written, so it carries no generated banner"));

        Assert.Empty(wrong);
    }

    [Fact]
    [Trait("Category", "fast")]
    [Trait("Value", "L3")]
    [Trait("Value", "A4")]
    public void Every_hand_written_file_holds_its_budget()
    {
        var over = Documents.Rows
            .Where(r => r.Kind == "hand" && r.Budget is not null && Repository.PhysicalLines(r.Path) > r.Budget)
            .Select(r => string.Create(CultureInfo.InvariantCulture, $"{r.Path}: {Repository.PhysicalLines(r.Path)} lines against its budget of {r.Budget} in ci/docs.manifest.json; shorten it"));

        Assert.Empty(over);
    }
}
