namespace Projection.Targets.SSDT

// LINT-ALLOW-FILE: the cutover apply-runbook emitter (wave B6 / ideation §12 F7).
//   A terminal Markdown artifact composed from the manifest's typed structure
//   (the deployment batches, the table + schema counts) — the same terminal-text
//   boundary the sibling bundle emitters own (PostDeployEmitter's SQL text,
//   ManifestEmitter's JSON). The order is DERIVED (the manifest's FK-safe Kahn
//   batches), never hand-authored prose; only the phase framing is literal.

open System.Text
open Projection.Core

/// Π_Runbook — the cutover-day apply runbook (ideation §12 F7). A numbered,
/// ORDERED apply manifest emitted WITH the SSDT bundle: schema → tables (in the
/// manifest's FK-safe deployment batches) → data → post-deploy → verify, each
/// step naming the precondition it stands on. Where `ManifestEmitter` produces
/// the machine manifest (`manifest.json`), this produces the operator's
/// checklist (`apply-runbook.md`) — the same structure, the human lens. The
/// deploy ORDER is the manifest's `DeploymentBatches` (Kahn-levels, dependency
/// depth ascending; tables within a batch have no FK dependency and may apply in
/// parallel), so the runbook is a true projection of the bundle, never static
/// prose that could drift from what the bundle actually contains.
[<RequireQualifiedAccess>]
module ApplyRunbookEmitter =

    /// The bundle-root file name — one convention, joined into the bundle map by
    /// `SsdtBundle.composeWithSchemas`.
    let fileName : string = "apply-runbook.md"

    /// The most batch members named on one step before the remainder is counted
    /// (THE_VOICE §12 — cap the breadth, name the remainder).
    [<Literal>]
    let private batchNameCap = 10

    let render (schemaCount: int) (manifest: ManifestEmitter.Manifest) : string =
        let sb = StringBuilder()
        let line (s: string) : unit = sb.AppendLine s |> ignore
        let tableCount = List.length manifest.Tables
        let batches = manifest.DeploymentBatches
        // The step numbering is a function of the batch count (Phase 2 has one
        // step per batch, or one fallback step when no topological order rode the
        // manifest), so every step number is computed — no render-loop mutation.
        let batchSteps = max 1 (List.length batches)
        let phase3Start = 2 + batchSteps

        line "# Apply runbook"
        line ""
        line "The cutover-day apply order for this bundle. Run the phases in sequence; within a"
        line "deployment batch the tables have no foreign-key dependency on one another and may be"
        line "applied in parallel. Each step names the precondition it stands on."
        line ""

        line "## Phase 1 — Schema"
        line (sprintf "1. Apply `Schemas/*.sql` (%d schema(s)). Precondition: the target database exists and you hold CREATE SCHEMA / ALTER." schemaCount)
        line ""

        line (sprintf "## Phase 2 — Tables (%d table(s) in %d FK-safe batch(es))" tableCount (List.length batches))
        if List.isEmpty batches then
            line (sprintf "2. Apply the %d per-table `.sql` file(s). Precondition: Phase 1 applied." tableCount)
        else
            batches
            |> List.iteri (fun i batch ->
                let names = batch |> List.map SsKey.rootOriginal
                let shown = names |> List.truncate batchNameCap
                let extra = List.length names - List.length shown
                let namesText =
                    if extra > 0 then sprintf "%s, and %d more" (String.concat ", " shown) extra
                    else String.concat ", " shown
                let precondition = if i = 0 then "Phase 1 applied" else sprintf "batch %d applied" i
                line (sprintf "%d. Batch %d — %d table(s) with no dependency within the batch: %s. Precondition: %s."
                        (2 + i) (i + 1) (List.length batch) namesText precondition))
        line ""

        line "## Phase 3 — Data and post-deploy"
        line (sprintf "%d. Static seeds — the model's declared reference data. Precondition: the tables (Phase 2) applied." phase3Start)
        line (sprintf "%d. Bulk data load — `Data/Bootstrap.sql`. NOT auto-run; the operator runs it. Precondition: Phase 2 applied." (phase3Start + 1))
        line (sprintf "%d. Re-trust foreign keys and enable CDC — the post-load pass. Precondition: the data loaded; you hold ALTER; CDC is enabled on the target." (phase3Start + 2))
        line ""

        line "## Phase 4 — Verify"
        line (sprintf "%d. `projection check fidelity <flow>` — prove the load row-faithful (drift · rows · CDC-silence). Precondition: Phases 1–3 complete." (phase3Start + 3))
        line ""

        line (sprintf "_%d table(s) · %d schema(s) · %d FK-safe deployment batch(es). Generated by projection; the order is the bundle's own dependency order._"
                tableCount schemaCount (List.length batches))
        sb.ToString()
