/* ==========================================================================
   Static Entity Seed Script
   Generated by OutSystems DDL Exporter
   This script merges reference data captured from static entities so that
   SSDT deployments remain idempotent across environments.
   --------------------------------------------------------------------------
   The blocks below are populated at generation time. Each block issues a
   MERGE statement scoped to a specific static entity.
   ==========================================================================
*/

SET NOCOUNT ON;

{{STATIC_ENTITY_BLOCKS}}
