-- Generated by sidecar/projection/scripts/ssdt-agent-package.mjs estate-kit-apply (ssdt-agent-package). Do not edit by hand; edit scripts/estate-kit/ and re-run.
/*
  Post-deployment — includes the seed. The seed is additive (MERGE without a
  delete arm) so republishing never prunes rows behind the acceptance's back.
*/
:r .\Data\Seed.sql
