module Projection.Tests.OssysTighteningOpportunitiesParityTests

// V1 parity audit — slice 5.4.γ.opportunities. Reserves matrix rows
// 77-84 (V1's Opportunity / diagnostic / reporting / remediation
// surface vs V2's Diagnostics writer + ManifestEmitter + LineageEvent
// + per-pass opportunityEntry). Rounds out the chapter 5.4 tightening
// audit triad (signals → evaluators → opportunities/reporting).

open Xunit

[<Fact(Skip = "Matrix row 77 — 🟡 DIVERGENCE. V1's `Opportunity.cs` (~196 LOC) is a per-decision opportunity record carrying Type+Title+Summary+Risk+Disposition+Category+Evidence (opaque array)+Rationales (string array)+EvidenceSummary+Columns — domain-specific fields tightly coupled to the tightening surface. V2's `Diagnostics.fs` `DiagnosticEntry` (lines 60-67) is structurally generic: Source+Severity+Code+Message+SsKey+Metadata (string-keyed map). V2 separates concerns: lineage events carry typed Outcome DUs (`NullabilityOutcome` / `UniqueIndexOutcome` / `ForeignKeyOutcome` — structurally accessible via pattern match); DiagnosticEntry carries prose narration + typed SsKey + Metadata for non-structural values. V1's risk classification + disposition reachable from V2's `LineageDiagnostics.payload |> .Decisions` (typed). See `DECISIONS 2026-05-18 (slice 5.4.γ.opportunities) — Per-pass DiagnosticEntry contract: typed outcomes in Lineage; prose narration in Diagnostics`. **Trigger to revisit**: consumer demands automated extraction of risk/disposition from the diagnostic stream (dashboard, alert routing); cash-out: lift risk + disposition into structured Metadata keys per the codified per-pass contract.")>]
let ``5.4.γ row 77: V1 Opportunity domain-specific record vs V2 generic DiagnosticEntry`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 77 + DECISIONS 2026-05-18 (slice 5.4.γ.opportunities)"

[<Fact(Skip = "Matrix row 78 — 🔵 V2-EXTENSION. V1's `OpportunityBuilder.cs` (~62 LOC) uses an imperative accumulator pattern — `TryCreate` consumes a decision + per-axis context, returns an Opportunity (or null when no diagnostic is warranted); caller accumulates into a mutable buffer. V2's per-pass `opportunityEntry` functions (e.g., `NullabilityPass.opportunityEntry` lines 117-170) inline emission via the writer monad: `LineageDiagnostics.tellDiagnostics` accumulates entries chronologically (A24 — earliest-first under bind); the pass returns `Lineage<Diagnostics<DecisionSet>>` (per `DECISIONS 2026-05-13 — Pass return-type codification`). V2's monad is applicative + composable across multi-pass pipelines; per-pass inlining leverages F# compiler exhaustiveness on the Outcome DU. The writer's `tellMany` primitive supports filtering at emission time (V2 emits only on `RequireOperatorApproval` + `RelaxedUnderEvidence` for nullability — other outcomes are structurally silent). Performance + ergonomics parity with V1's builder; V2 stronger via compile-checked exhaustiveness + composability.")>]
let ``5.4.γ row 78: V1 OpportunityBuilder mutable accumulator vs V2 writer-monad applicative emission`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 78"

[<Fact(Skip = "Matrix row 79 — 🟠 NOT-MAPPED. V1's `OpportunitiesReport.cs` (~23 LOC) is a top-level columnar aggregate (`Columns : ColumnOpportunityReport[]` + `Summary : ReportSummary`) with rolled-up metrics (`ColumnCount`, `ColumnsWithOpportunities`, `OpportunityMetrics`); produced by `PolicyDecisionReporter.Create`. V2 has no equivalent top-level aggregate — `Diagnostics<DecisionSet>` carries entries; pass outputs carry decisions; rollup is the consumer's responsibility. **Cash-out shape**: a thin V2 module `Projection.Targets.OperationalDiagnostics.OpportunitiesReport` consuming `Diagnostics.Entries` filtered by Severity/Code + grouped by intervention, producing per-axis summary metrics (column tightening rollup; unique-index coverage; FK coverage). Lives at the emission boundary per A36 (realization-layer policy, not Pass responsibility). **Dependencies**: independent of all other slice 5.4.γ.opportunities rows; consumes the per-pass `DiagnosticEntry` stream. **Trigger**: operator dashboard demands per-axis rollup metrics, OR `ManifestEmitter` surface expands to carry the rollup. **Acceptance**: parity test on a shared decision corpus asserts V1's `ReportSummary.ColumnCount` / `ColumnsWithOpportunities` rollups equal V2's projection from the diagnostic stream.")>]
let ``5.4.γ row 79: V1 OpportunitiesReport + ReportSummary top-level aggregate lifts to V2 emitter-side projection`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 79"

[<Fact(Skip = "Matrix row 80 — 🟢 PARITY. V1's `Tightening/PolicyDecisionReporter.cs` (~326 LOC) is the choreographer that walks nullability + unique-index + FK decision dictionaries; constructs per-axis reports (ColumnDecisionReport / UniqueIndexDecisionReport / ForeignKeyDecisionReport); aggregates per-module rollups (ModuleDecisionRollups). V2's choreography is **distributed across two layers**: (a) pass drivers (`NullabilityPass.run` / `UniqueIndexPass.run` / `ForeignKeyPass.run`) each produce `Lineage<Diagnostics<DecisionSet>>` in deterministic order; (b) `ManifestEmitter` (in `Projection.Targets.OperationalDiagnostics`) consumes the per-pass outputs + the diagnostic stream, builds the manifest JSON. **Output properties identical**: per-axis decisions accessible by SsKey; per-module rollups computable from the decision sets; T11 sibling-keyset coverage (every decision emits one Annotated event). V1 sorts output by schema/table/column at emission boundary; V2 preserves Lineage trail ordering (A24) + diagnostic entry order (chronological). Structure differs (V1 imperative walk vs V2 applicative pass + emitter) but reachability + cardinality are identical.")>]
let ``5.4.γ row 80: V1 PolicyDecisionReporter (326 LOC choreographer) ↔ V2 distributed pass + ManifestEmitter PARITY`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 80"

[<Fact(Skip = "Matrix row 81 — 🟠 NOT-MAPPED. V1's `Tightening/PolicyDecisionSummaryFormatter.cs` (~439 LOC) is V1's biggest formatter — produces operator-facing summary tables. Walks `ColumnDecisionReport[]`; classifies each decision into 6 buckets (Mandatory / ForeignKey / PrimaryKey / Unique / Physical / Remediation); emits prose summaries per bucket with mode-aware narration; produces `ImmutableArray<string>` console output. V2 has no equivalent summary surface — DiagnosticEntry.Message field carries prose per entry, but bucket aggregation + summary tables are not produced anywhere. **Cash-out shape**: a `SummaryFormatter` consumer module taking `Diagnostics<DecisionSet> × NullabilityMode` and producing `string list` (or JSON SummaryReport) mirroring V1's per-bucket prose. Per bucket: count, entity count, key rationales, mode-aware narration. Lives at the CLI surface (`Projection.Cli/Program.fs`) or operational-diagnostics emission boundary. **Dependencies**: ManifestEmitter chapter 4.4 close (shipped); SummaryFormatter consumer lands chapter 5+ (operator-facing CLI polish) or deferred to chapter 6 (post-cutover UX optimization). **Determinism**: V1's prose is deterministic (no randomness; only mode/counts vary); V2's diagnostics stream is also deterministic (A24 chronological order); the projection is structurally deterministic. **Trigger**: V2 CLI standardizes on summary output format before cutover, OR operator workflow demands V1-compatible bucket-wise summary prose. **Acceptance**: parity test on a shared decision corpus asserts V1's `FormatForConsole` output equals V2's `SummaryFormatter.format` output line-by-line.")>]
let ``5.4.γ row 81: V1 PolicyDecisionSummaryFormatter (439 LOC operator-facing summary) lifts to V2 SummaryFormatter consumer`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 81"

[<Fact(Skip = "Matrix row 82 — 🔵 V2-EXTENSION. V1's `Tightening/TighteningDiagnostic.cs` (~83 LOC) is purpose-built for tightening diagnostics: Code+Message+Severity+LogicalName+CanonicalModule+CanonicalSchema+PhysicalName+Candidates (array for duplicate-entity findings)+ResolvedByOverride. Extending to a new diagnostic source (e.g., adapter-layer / emitter-layer) requires defining a new type. V2's `Diagnostics.DiagnosticEntry` (in `Projection.Core/Diagnostics.fs` lines 60-67) is generic across all producer contexts: Source (names producer — `adapter:<name>` / `pass:<name>` / `emitter:<name>`) + Severity + Code (dot-separated routing prefix per `DECISIONS 2026-05-11`) + Message + SsKey (typed identity) + Metadata (`Map<string, string>` for non-structural values). One type covers tightening passes + adapters + emitters + future diagnostic sources. V1's mandatory-null-conflict diagnostic (TighteningDiagnostic.CreateMandatoryNullConflict, lines 24-46) constructs a tightening-specific diagnostic with prose Message + remediation query; V2's NullabilityPass.opportunityEntry emits a DiagnosticEntry with typed Outcome (RelaxedUnderEvidence / RequireOperatorApproval) + typed SsKey pointing to the attribute + Metadata carrying interventionId + numeric thresholds. **V2's generic shape is structurally more reusable**; same operator-visible information; better composability across producer surfaces.")>]
let ``5.4.γ row 82: V1 tightening-specific TighteningDiagnostic vs V2 generic DiagnosticEntry (V2 reusable)`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 82"

[<Fact(Skip = "Matrix row 83 — 🟠 NOT-MAPPED. V1's `Tightening/RemediationQueryBuilder.cs` (~73 LOC) emits remediation SQL (3-option UPDATE/DELETE/SELECT) operators run to fix data before tightening. V1 couples diagnostic production to remediation-SQL generation — `ColumnDecisionAggregator` line 116 calls `TighteningDiagnostic.CreateMandatoryNullConflict` which embeds the query. V2 has NO `RemediationEmitter` today — `ManifestEmitter.fs` shows the PreRemediation manifest field remains empty per `V2_DRIVER.md §154` (RemediationEmitter is explicitly scheduled as a chapter 5+ deferred deliverable). **Cash-out shape**: a `RemediationEmitter` module as sibling to `ManifestEmitter`, taking `Diagnostics<DecisionSet>` and producing `manifest.remediation.sql` with per-diagnostic UPDATE/DELETE/SELECT options. SQL is deterministic (SsKey + decision outcome determine the fix); ordering chronological per A24-equivalent. Lives in `Projection.Targets.OperationalDiagnostics/`. **Risk**: if chapter 5 doesn't ship before cutover, V2's operator UX for mandatory-null-conflict remediation degrades — operators see the diagnostic Message but must hand-write the UPDATE query (V1 provided the template). **Mitigation**: DiagnosticEntry.Message + Metadata carry full context (null count, budget, intervention ID); operators can infer fix semantics. Fallback remediation doc would substitute. **Trigger**: chapter 5+ RemediationEmitter slice opens, OR cutover dry-run discovers mandatory-null-conflict cases requiring SQL templates. **Acceptance**: a round-trip test asserts V2's emitted UPDATE/DELETE/SELECT options apply cleanly + produce the expected post-remediation state.")>]
let ``5.4.γ row 83: V1 RemediationQueryBuilder lifts to V2 RemediationEmitter (chapter 5+ deferred per V2_DRIVER §154)`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 83 + V2_DRIVER §154"

[<Fact(Skip = "Matrix row 84 — ⚫ V1-SUNSET. V1's `Tightening/TighteningRationales.cs` (~31 LOC) is a static module with ~30 `public const string` rationale labels (PrimaryKey, PhysicalNotNull, UniqueNoNulls, DataNoNulls, DataHasNulls, Mandatory, DeleteRuleIgnore, ProfileMissing, etc.). Decisions carry `ImmutableArray<string> Rationales` (ColumnDecisionReport line 298, UniqueIndexDecisionReport line 322, ForeignKeyDecisionReport line 307); `PolicyDecisionSummaryFormatter` pattern-matches on these strings (lines 72-95: `HasRationale(column, TighteningRationales.PrimaryKey)` etc.) to drive bucket classification. V2 replaces this with **typed outcome DUs** — every decision pathway branches on a closed variant (e.g., `NullabilityOutcome.EnforceNotNull(PrimaryKey)` / `KeepNullable(RelaxedUnderEvidence)` / `RequireOperatorApproval(MandatoryButHasNullsBeyondBudget)`); the Evidence is structurally embedded in the variant payload (null count, row count, budget). **Sunset rationale**: V1's string-based rationale surface was the UI anchor for filtering — operators queried decisions by rationale name (e.g., all `Mandatory` decisions). V2's lineage events carry typed outcomes; per-pass diagnostics carry Severity + Code (structured filters via dot-prefix per `DECISIONS 2026-05-11`); the string rationale is no longer load-bearing. **Migration impact**: `PolicyDecisionSummaryFormatter`'s bucket classification (V1's HasRationale string-match) becomes an outcome DU pattern-match in the V2 SummaryFormatter consumer (matrix row 81). The `TighteningRationales` constants retire; the Evidence payloads on Outcome variants carry the semantic content. Covered by slice 5.4.β.nullability row 69 (V1 string-rationale accumulation vs V2 typed evidence per outcome variant) at the per-pass level; this row records the module-level sunset.")>]
let ``5.4.γ row 84: V1 TighteningRationales string-constant module sunsets — V2 typed outcome DUs subsume`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 84"

[<Fact>]
let ``5.4.γ.opportunities: tightening-opportunities parity file present`` () =
    Assert.True(true)
