module Projection.Tests.OssysProfilingAcquisitionParityTests

// V1 parity audit — slice 5.4.δ.profiling. Reserves matrix rows
// 85-94 (V1's 28-file Profiling cluster vs V2's Profile module +
// ReadSide/ProfileSnapshot adapters). The OperatorIntent evidence
// axis per A34.

open Xunit

[<Fact(Skip = "Matrix row 85 — 🟠 NOT-MAPPED. V1's `Pipeline/Profiling/SqlDataProfiler.CaptureAsync()` is the live-probe orchestration entry — collects tables, loads metadata, builds plans, executes queries in parallel; concrete implementation of `IDataProfiler` for single-environment live SQL Server. V2's `Profile` aggregate is the OUTPUT contract (`Projection.Core/Profile.fs`); live-probe acquisition logic is DEFERRED. V2 ships `ReadSide` (catalog structure only) + `ProfileSnapshot.attach` (V1-JSON adapter); no orchestration of live SQL probes against an OSSYS-source database in V2 shipped code. **Cash-out shape**: `LiveProfiler` adapter module in `Projection.Adapters.Sql` carrying `readProfileAsync : SqlConnection -> Catalog -> Task<Result<Profile>>`. Dependencies: requires the per-probe query builders (rows 86-89) + sampling policy (row 90). **Trigger**: chapter 4.1.B § 4 or later — data-triumvirate slice calls for live SqlServer profile capture matching V1's evidence surface.")>]
let ``5.4.δ row 85: V1 SqlDataProfiler live-probe orchestration lifts to V2 LiveProfiler adapter`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 85"

[<Fact(Skip = "Matrix row 86 — 🟠 NOT-MAPPED. V1's `Pipeline/Profiling/NullCountQueryBuilder.BuildCommandText()` emits `SELECT SUM(CASE WHEN [col] IS NULL ...)` over sampled rows via `TOP (@SampleSize)` or full scan; structural query: CTE Source + per-column UNION ALL with grouped null counts. V2's `Profile.Columns` carries `NullCount : int64` + `NullCountProbeStatus : ProbeStatus`; the IR is fully carried; acquisition absent. **Cash-out shape**: F# module `NullCountProbe` with `queryText : schema:string -> table:string -> columns:string[] -> sampling:int option -> string` + `parseResult : seq<string * int64> -> Map<string, int64>`. Counts are exact (int64), not statistical (no decimal needed per `DECISIONS 2026-05-13 — Decimal as default for continuous statistical evidence` — applies to distributions, not counts). **Trigger**: same as row 85 — LiveProfiler chapter opens.")>]
let ``5.4.δ row 86: V1 NullCountQueryBuilder probe lifts to V2 NullCountProbe module`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 86"

[<Fact(Skip = "Matrix row 87 — 🟠 NOT-MAPPED. V1's `Pipeline/Profiling/UniqueCandidateQueryBuilder.BuildCommandText()` emits per-candidate uniqueness check via `SELECT CandidateId, CASE WHEN EXISTS (GROUP BY ... HAVING COUNT(*) > 1) ...`; composite (multi-column) + single-column variants share the same builder. V2's `Profile.UniqueCandidates : UniqueCandidateProfile list` + `Profile.CompositeUniqueCandidates : CompositeUniqueCandidateProfile list` carry the IR; V2 added `ProbeStatus` to `CompositeUniqueCandidateProfile` (V1 lacked it — uncertainty about probe execution). Acquisition absent. **Cash-out shape**: F# module `UniqueCandidateProbe` with `queryText : schema:string -> table:string -> candidates:(string[] * key:string)[] -> sampling:int option -> string` + `parseResult : seq<string * bool> -> Map<string, bool>`. Per pillar 8 — V1's `UniqueCandidatePlan.Key` serialized string maps to V2's `SsKey` (source Attribute identity); cash-out must reconcile coordinate-to-SsKey resolution at adapter boundary (same pattern as `ProfileSnapshot`). **Trigger**: same as row 85.")>]
let ``5.4.δ row 87: V1 UniqueCandidateQueryBuilder probe lifts to V2 UniqueCandidateProbe module`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 87"

[<Fact(Skip = "Matrix row 88 — 🟠 NOT-MAPPED (partial — metadata probe shipped). V1's `Pipeline/Profiling/ForeignKeyProbeQueryBuilder` has two methods: (a) `BuildRealityCommandText()` emits per-FK orphan count via `LEFT JOIN target WHERE source.col IS NOT NULL AND target.col IS NULL`; (b) `BuildMetadataCommandText()` queries `sys.foreign_keys` for TRUSTED / NO CHECK flags. V2's `Profile.ForeignKeys : ForeignKeyReality list` carries `HasOrphan : bool` + `OrphanCount : int64` + `IsNoCheck : bool` + `ProbeStatus`. **ReadSide already queries FK metadata** (`Projection.Adapters.Sql/ReadSide.fs §227-278 readForeignKeys`); the metadata probe is COVERED. Orphan-count probe absent. **Cash-out shape**: F# module `ForeignKeyProbe` with `realityQueryText : schema:string -> table:string -> fks:(string * targetSchema:string * targetTable:string * targetColumn:string)[] -> sampling:int option -> string` + `parseResult : seq<string * int64> -> Map<string, int64>`. Paired with row 89 (orphan sample). **Trigger**: same as row 85.")>]
let ``5.4.δ row 88: V1 ForeignKeyProbeQueryBuilder orphan-count probe lifts to V2 ForeignKeyProbe module`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 88"

[<Fact(Skip = "Matrix row 89 — 🟠 NOT-MAPPED. V1's `Pipeline/Profiling/ForeignKeyOrphanSampleQueryBuilder.BuildCommandText()` emits `SELECT TOP (@SampleLimit)` of orphan rows with PK identifiers + orphan value + `TotalOrphans` count (subquery); deterministic sampling for operator-facing diagnostics. **Distinct from orphan COUNT (row 88)** — this extracts the row sample for operator visibility. V2's `Profile.ForeignKeys` has NO `OrphanSample` field; IR carries the count but NOT the row identifiers. **Rationale for absence**: V1's orphan sample is operational diagnostics (operator reads it to understand constraint violations), not data-intent evidence. Per pillar 9, V2's Profile carries data-intent evidence only; operational samples land in `Diagnostics<'output>` (observer-relevant surface). **Cash-out shape**: add `OrphanSamples : ForeignKeyOrphanSample option` to `Profile.ForeignKeys` OR parallel `Map<SsKey, ForeignKeyOrphanSample>` when consumer demands surface. `ForeignKeyOrphanSample = { PrimaryKeyColumns: SsKey[]; ForeignKeyValue: SqlLiteral; SampleRows: Row[]; TotalOrphans: int64 }`. **Trigger**: chapter 4.2 (User FK reflow) or a diagnostics writer needs to surface per-FK orphan rows to operators.")>]
let ``5.4.δ row 89: V1 ForeignKeyOrphanSampleQueryBuilder operator-facing surface lifts to V2 diagnostics axis`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 89"

[<Fact(Skip = "Matrix row 90 — 🟡 DIVERGENCE. V1's `Pipeline/Profiling/TableSamplingPolicy.ShouldSample()` + `GetSampleSize()` are per-table heuristics deciding whether to sample (row count > threshold) and at what size (min of sample-size config, row count, max-rows-per-table). Configuration via `SqlProfilerOptions.Sampling.RowCountSamplingThreshold` + `SampleSize` + `Limits.MaxRowsPerTable`. V2's `Profile` carries `ProbeStatus.SampleSize : int64` (what sample size WAS used) but no sampling POLICY in Core; `ReadSide` does full-table catalog read (no sampling). See `DECISIONS 2026-05-18 (slice 5.4.δ.profiling) — Sampling policy is operator intent; lives in the orchestrator, not in Profile IR`. Trade-off: V2 loses V1's heuristic constraint-checking surface (`SqlProfilerOptions` prevents nonsensical configs). Accepted: policy lives in Pipeline layer's Config module per run; Profile is witness-only. **Re-open trigger**: LiveProfiler cash-out (row 85) lands — sampling heuristic ports as a private helper in the adapter, not lifted to Core.")>]
let ``5.4.δ row 90: V1 TableSamplingPolicy heuristic vs V2 Profile.ProbeStatus witness-only`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 90 + DECISIONS 2026-05-18 (slice 5.4.δ.profiling)"

[<Fact(Skip = "Matrix row 91 — 🔵 V2-EXTENSION. V1's `Pipeline/Profiling/ProfilingPlans.cs` + `ProfilingPlanBuilder.cs` are explicit per-table plans carrying probe declarations for all columns, unique candidates, FKs; plan building is pre-probe orchestration: resolve physical coordinates, validate against metadata, emit structured probe-execution plans. `BuildUniqueKey()` and `BuildForeignKeyKey()` are deterministic key builders for plan indexing. V2's `Catalog` + `Policy` together specify what should be probed; `Profile` is the output; **no explicit plan structure**. Plan-building is implicit: adapter at runtime decides which columns/FKs to probe based on Catalog structure. `ProbeStatus` carries success metadata, not a pre-flight plan. V2's approach trades explicitness for flexibility (adapter can apply real-time filtering, e.g., skip an FK because target doesn't exist in catalog). **Re-open trigger**: observability becomes a requirement (operator wants to see what plan was used per table) → future `ProbeSpec` IR added to Config or Diagnostics. Per `DECISIONS 2026-05-07 — IR grows under evidence`. Today deferred.")>]
let ``5.4.δ row 91: V1 ProfilingPlans explicit pre-flight vs V2 adapter-time implicit (V2 flexible)`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 91"

[<Fact(Skip = "Matrix row 92 — 🟠 NOT-MAPPED. V1's `Pipeline/Profiling/MultiTargetSqlDataProfiler.CaptureAsync()` orchestrates parallel profile captures across multiple environments (dev/uat/prod), merges results via worst-case aggregation (`MergeSnapshots`); consensus thresholding + comprehensive null/unique/FK aggregation. `ProfilingEnvironmentSnapshot` captures per-environment result + duration. V2's `Profile` structure is environment-agnostic; multi-environment aggregation NOT in shipped V2. `Profile.empty` exists; no `Profile.union` / `Profile.aggregate` / `Profile.merge`. `ReadSide.read` is single-environment. **Rationale for absence**: multi-environment profiling is operator-intent (policy: which environments to poll, how to merge); not data-intent per A34. **Cash-out shape**: `Profile.merge : Profile -> Profile -> Profile` function + property test that merge is commutative + associative; consensus thresholding lands in the orchestrator (Projection.Pipeline), not in Profile. Worst-case-aggregation strategy ports V1's `AggregateProbeStatus` + `AggregateNullRowSample` patterns. **Trigger**: data-triumvirate work calls for multi-environment risk scoring (chapter 4.1.B or 4.2).")>]
let ``5.4.δ row 92: V1 MultiTargetSqlDataProfiler multi-environment aggregation lifts to V2 Pipeline orchestrator`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 92"

[<Fact(Skip = "Matrix row 93 — 🟢 PARITY (refined). V1's `Pipeline/Profiling/ProfilingSnapshotNormalizer.cs` + `ProfilingStandardizationValidator.cs` enforce shape invariants on profile snapshots (row counts ≥ null counts; null percentages bounded; composite keys have >0 columns); validation-error reporting. V2's smart constructors (`ColumnProfile.create`, `UniqueCandidateProfile.create`, `NumericDistribution.create`) carry invariant enforcement structurally via `Result<'a>`. `ColumnProfile.create` rejects `nullCount > rowCount` (Profile.fs line 128). `NumericDistribution.create` enforces monotonicity + sample-size floor. Degenerate cases accepted, not rejected (e.g., `Min = Max` valid; all-null column valid per `isAllNull` predicate). **Reconciliation**: V1's normalizer/validator are runtime guards catching malformed inputs from the profiler; V2's smart constructors are structural guards — by-construction enforcement. The shift from runtime validation (V1: catch-then-report) to compile-time / construction-time (V2: reject invalid by type) is V2-deliberate per `AXIOMS.md` structural-commitment-via-construction-validation. **No cash-out needed** — discipline already applied; test coverage confirmed in Profile tests.")>]
let ``5.4.δ row 93: V1 normalizer + validator runtime guards ↔ V2 smart-constructor structural guards PARITY`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 93"

[<Fact(Skip = "Matrix row 94 — 🔵 V2-EXTENSION. V1's `Pipeline/Profiling/FixtureDataProfiler` is an offline-test fixture implementation of `IDataProfiler` reading JSON from disk; deserializes `ProfileSnapshot` JSON into in-memory `ProfileSnapshot`. V2's offline fixture path is **three-part composition**: (1) `Catalog` via `ReadSide` on a fixture DB or in-memory rowset bundle; (2) `Profile.empty` for skeleton-only tests; (3) `ProfileSnapshot.attach` to parse V1-format JSON into V2 `Profile`. V2's approach decoupled Profile input from Catalog — a single fixture Catalog can be tested against multiple Profile evidence sets (skeleton-only, full profile, partial profile) by composing `Profile.empty`, `ProfileSnapshot.attach`, `ProfileStatistics.attach`. **FixtureDataProfiler equivalent**: not needed as a single monolithic class; tests use `let fixture = ProfileSnapshot.attach catalog jsonText` inline. **Documentation cash-out**: CLAUDE.md / PLAYBOOK.md section naming the composition pattern (per-concern factoring + functional composition); not a code debt; a documentation debt.")>]
let ``5.4.δ row 94: V1 FixtureDataProfiler monolith vs V2 fixture-composition pattern (V2 stronger)`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 94"

[<Fact>]
let ``5.4.δ.profiling: profiling-acquisition parity file present`` () =
    Assert.True(true)
