module Projection.Tests.OssysTighteningNullabilityParityTests

// V1 parity audit — slice 5.4.β.nullability. Reserves matrix rows
// 64-70 (V1's signal-combinator nullability architecture vs V2's
// typed NullabilityRules + NullabilityPass).

open Xunit

[<Fact(Skip = "Matrix row 64 — 🔵 V2-EXTENSION. V1's nullability evaluation uses a signal-combinator architecture: abstract base `NullabilitySignal` + recursive composition via `AllOfSignal` / `AnyOfSignal` + 2-valued boolean `SignalEvaluation.Result` + flat-string rationale accumulation via `CollectRationales()`. The root signal is an AnyOf tree assembled by `NullabilitySignalFactory` from a per-mode `NullabilityModeDefinition`. V2's `NullabilityRules.evaluate` (in `Projection.Core/Strategies/NullabilityRules.fs`) uses a typed-strategy architecture: `StrategyEvaluator<'context, 'config, 'decision>` function-type seam + closed-DU outcome (`NullabilityOutcome`) + linear if-elif sequence over the decision hierarchy + structured-typed-evidence per outcome variant. Same outcomes on shared inputs; V2's type-level evidence is load-bearing for downstream emitter consumers + canary per-decision audit trail. Covered by `DECISIONS 2026-05-11 — Strategy-layer codification`. No new DECISIONS needed.")>]
let ``5.4.β.nullability row 64: V1 signal-combinator architecture vs V2 typed-strategy architecture`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 64"

[<Fact(Skip = "Matrix row 65 — 🔵 V2-EXTENSION. V1's `SignalEvaluation.Result` is 2-valued (true/false); when a mandatory column has nulls beyond budget AND tightening options forbid silent relaxation, V1 returns `false` AND surfaces an Opportunity record with `Disposition.NeedsRemediation` — the decision is deferred via out-of-band metadata. V2's `NullabilityOutcome` carries a **third variant** `RequireOperatorApproval` (carrying typed `NullabilityConflict` evidence). The third state is **in the main decision type**, not a side-channel — downstream consumers can pattern-match it with F# exhaustiveness checking. See `DECISIONS 2026-05-18 (slice 5.4.β.nullability) — Ternary outcome space for operator-approval decision lifting`. The pattern applies symmetrically to UniqueIndexOutcome + ForeignKeyOutcome (sibling strategies).")>]
let ``5.4.β.nullability row 65: V1 2-valued + opportunity-record vs V2 3-variant outcome (operator-approval lifting)`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 65 + DECISIONS 2026-05-18 (slice 5.4.β.nullability)"

[<Fact(Skip = "Matrix row 66 — 🔵 V2-EXTENSION. V1's `UniqueCleanSignal` and `ForeignKeySupportSignal` live under `Osm.Validation/Tightening/Signals/` and participate in the **nullability** AnyOf root tree (mode-dependent: TelemetryOnly in Cautious; Tighten in Aggressive). V2 **separates** these into independent registered-intervention strategies: `UniqueIndexRules` + `UniqueIndexPass` (own outcome `UniqueIndexOutcome = EnforceUnique | DoNotEnforce | RequireOperatorApproval`); `ForeignKeyRules` + `ForeignKeyPass` (own outcome `ForeignKeyOutcome = EnforceConstraint | DoNotEnforce | RequireOperatorApproval`). V2's axis separation is principled per pillar 9 (harvest-dichotomy) — tightening / uniqueness / FK are orthogonal decision axes; bundling them under a single signal tree (V1) conflates concerns. Each axis runs its own pass; lineage events are per-axis classified. Acceptance: per-axis property tests assert independence (changing nullability config doesn't change unique-index decisions).")>]
let ``5.4.β.nullability row 66: V1 UniqueClean + FK signals nested under nullability vs V2 axis-separated registered interventions`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 66"

[<Fact(Skip = "Matrix row 67 — ⚫ V1-SUNSET. V1's `DefaultSignal` checks `!string.IsNullOrWhiteSpace(context.Attribute.DefaultValue)` and emits a rationale when the attribute is also mandatory — but `Participation = TelemetryOnly` across all modes, so it **never causes tightening**. V2 omits the signal entirely from `NullabilityRules.evaluate`. Sunset rationale: presence of a DEFAULT clause does not prevent NULL inserts (`INSERT INTO t (col) VALUES (NULL)` inserts NULL even with DEFAULT present); therefore DEFAULT is not a signal for nullability tightening. V1's inclusion was telemetry-only and structurally misleading (suggests DEFAULT influences nullability when it does not); V2's omission removes the noise signal. Migration impact: zero (V1's signal was telemetry-only; no downstream consumer changed behavior based on it).")>]
let ``5.4.β.nullability row 67: V1 DefaultSignal sunsets — V2 correctly omits as semantic noise`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 67"

[<Fact(Skip = "Matrix row 68 — 🔵 V2-EXTENSION. V1's `RequiresEvidenceSignal` is a higher-order combinator: wraps an inner signal + evidence signal; evaluates inner first, returns false immediately on inner=false; else returns evidence.Result. V2 **inlines** the evidence check directly into the atomic decision rule — `NullabilityRules.evaluate`'s Mandatory branch checks profile inline and carries typed evidence values (`NullCount`, `RowCount`, `NullBudget`) into the decision outcome (`LogicalMandatoryNoProfile` / `LogicalMandatoryNoNulls rowCount` / `LogicalMandatoryWithinBudget` / `RequireOperatorApproval (MandatoryButHasNullsBeyondBudget)`). V2's inlining: (a) eliminates the higher-order indirection; (b) makes evidence values available to the structured outcome (V1 collected them only as string rationales); (c) preserves all decision outcomes. No DECISIONS needed — pillar 1 (data-structure-oriented over higher-order combinator) already covers.")>]
let ``5.4.β.nullability row 68: V1 RequiresEvidenceSignal higher-order combinator vs V2 inline evidence with typed outcome`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 68"

[<Fact(Skip = "Matrix row 69 — 🔵 V2-EXTENSION. V1's `SignalEvaluation.Rationales : ImmutableArray<string>` accumulates flat-string rationales recursively via `CollectRationales()` — descendants' rationales bubble up to the root. Strings: `Mandatory`, `DataHasNulls`, `NullBudgetEpsilon`, `PrimaryKey`, etc. V2's evidence is **typed** — each `NullabilityOutcome` variant carries its specific evidence as typed fields (`LogicalMandatoryWithinBudget` carries `nullCount: int64 * rowCount: int64 * budget: decimal`); the `NullabilityEvidence` module + `NullabilityPass.opportunityEntry` render to diagnostic strings at the boundary only. Pillar 1 (data-structure-oriented over string-parsing): V2 carries typed structures end-to-end; strings emerge only at the absolute terminal boundary (manifest emitter / diagnostics writer). Downstream consumers (emitters, canary validators) consume typed evidence directly without re-parsing string rationales.")>]
let ``5.4.β.nullability row 69: V1 string rationale accumulation vs V2 typed evidence per outcome variant`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 69"

[<Fact(Skip = "Matrix row 70 — 🟢 PARITY (omnibus, 4 atomic signals). V1's four atomic nullability-tightening signals — `PrimaryKeySignal` (always tightens if IsIdentifier), `PhysicalNotNullSignal` (always tightens if !IsNullable in physical schema), `MandatorySignal` (tightens if IsMandatory + profile evidence within budget), `NullEvidenceSignal` (evidence-gating helper for Mandatory) — all map to corresponding branches in V2's `NullabilityRules.evaluate`: (1) operator-override short-circuit (matches V1's TighteningOptions.Overrides; V2 typed via `NullabilityTighteningConfig.shouldKeepNullable`); (2) `EnforceNotNull(PrimaryKey)` if `attribute.IsPrimaryKey`; (3) `EnforceNotNull(PhysicallyNotNull)` if `not attribute.Column.IsNullable`; (4) `EnforceNotNull(LogicalMandatoryNoProfile|NoNulls|WithinBudget)` or `KeepNullable(RelaxedUnderEvidence)` or `RequireOperatorApproval(MandatoryButHasNullsBeyondBudget)` per evidence-budget logic. Same conditions, same source-of-truth (logical schema for IsMandatory; physical schema for IsNullable; profile for NullCount/RowCount). Acceptance: a property test would assert outcome equivalence on a shared `(attribute, profile, config)` fixture against V1's signal-tree evaluation.")>]
let ``5.4.β.nullability row 70: V1 4 atomic nullability signals ↔ V2 NullabilityRules.evaluate branches PARITY`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 70"

[<Fact>]
let ``5.4.β.nullability: nullability parity file present`` () =
    Assert.True(true)
