module Projection.Tests.OssysCliVerbsParityTests

// V1 parity audit — slice 5.7.α.cli. Reserves matrix rows 105-119
// (V1's 12-verb CLI surface vs V2's 4-verb Projection.Cli). Opens
// chapter 5.7 (operator affordances). Most rows 🟠 NOT-MAPPED with
// explicit cash-out shapes; V2's CLI is deliberately minimal at
// launch.

open Xunit

[<Fact(Skip = "Matrix row 105 — 🟢 PARITY. V1's `Osm.Cli/Commands/BuildSsdtCommandFactory.cs` (build-ssdt verb) consumes V1 JSON model + profile + filters → emits SSDT artifact bundle (dacpac + distributed scripts). V2's `projection emit <input> <out>` (Program.fs lines 106-129) consumes V1 JSON model + writes SSDT artifacts to output dir. **Primary operator workflow** maps directly. V1's `--open-report` extension (`OpenReportVerbExtension`) opens SSDT in SSMS — V2 omits at launch (covered separately at row 115). Core capability identical; report-opening is infrastructure.")>]
let ``5.7.α row 105: V1 build-ssdt verb ↔ V2 projection emit PARITY`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 105"

[<Fact(Skip = "Matrix row 106 — 🟡 DIVERGENCE. V1's `Osm.Cli/Commands/FullExportCommandFactory.cs` (full-export verb) orchestrates extraction → profiling → emission → load-harness replay → final SSDT bundle in one verb. V2 deliberately decomposes: `emit` is pure projection; deploy + harness replay are external orchestration. See `DECISIONS 2026-05-18 (slice 5.7.α.cli) — V2 CLI deliberately minimal: production-deferred posture; reopen per verb on operator demand`. **Rationale**: A36 (bulk-vs-incremental is realization policy); harness belongs outside Π (per chapter 3.1 A35/A36 cash-out). **Cash-out**: future `osm batch-replay` verb if operator demand for integrated load-harness surface materializes; today operators chain `osm emit && osm deploy && <run-harness>` explicitly.")>]
let ``5.7.α row 106: V1 full-export orchestrated verb vs V2 decomposed pipeline (V2 principled per A36)`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 106 + DECISIONS 2026-05-18 (slice 5.7.α.cli)"

[<Fact(Skip = "Matrix row 107 — 🟠 NOT-MAPPED. V1's `Osm.Cli/Commands/ExtractModelCommandFactory.cs` (extract-model verb) consumes OSSYS database connection + module filters + SQL overrides → V1 JSON model file (extracted via Advanced SQL). V2 assumes model pre-extracted (config-driven input path); no standalone extract verb at launch. **Cash-out shape**: minimal wrapper on V2's OSSYS adapter — `osm extract <connection-string> --modules <csv> --out <path>`; wraps `Projection.Adapters.OssysSql.MetadataSnapshotRunner.runAsync` + writes Catalog as JSON. ~50 LOC. **Dependencies**: chapter 5.1.γ production wiring (matrix rows 32-36) — transient retry + connection lifecycle. **Trigger**: V2 production CLI surface ships; operators need extraction as a CLI step (today extraction is V1-owned during R6 split-brain cutover window).")>]
let ``5.7.α row 107: V1 extract-model verb lifts to V2 osm extract wrapper on OssysSql adapter`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 107"

[<Fact(Skip = "Matrix row 108 — 🟠 NOT-MAPPED. V1's `Osm.Cli/Commands/ProfileCommandFactory.cs` (profile verb) consumes V1 JSON model + SQL connection → profile snapshot JSON carrying row-count + NULL-count distributions. V2 embeds profiling logic in Π via the LiveProfiler adapter (row 85 cash-out shape); standalone verb deferred. **Cash-out shape**: `osm profile <input-model> <connection-string> --out <profile.json>`; wraps the LiveProfiler adapter + writes Profile as V1-compatible JSON. **Dependencies**: row 85 (LiveProfiler module ships) — once that lands, the CLI wrapper is ~30 LOC. **Trigger**: operators demand profile-only execution (for diagnostic/tuning iteration before committing to a full emit). Core capability exists in `ColumnProfile` / `DistributionSnapshot`.")>]
let ``5.7.α row 108: V1 profile verb lifts to V2 osm profile wrapper on LiveProfiler adapter`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 108"

[<Fact(Skip = "Matrix row 109 — ⚫ V1-SUNSET. V1's `Osm.Cli/Commands/DmmCompareCommandFactory.cs` (dmm-compare verb) consumes SSDT bundle + DMM baseline → comparison report (diff artifact + exit code). V1's DMM lens machinery is sunset per slice 5.8.α (matrix rows 40-41); V2's comparison axis is **PhysicalSchema round-trip equivalence** (the canary; matrix row 44) — V1's DMM-style artifact diffing is orthogonal. V2's `projection canary <ddl>` verb is the cutover-fidelity gate, not a DMM diff. **Future replacement** (operator concept reserved at matrix row 41): `projection compare <left> <right>` with closed-DU `DiffSource = LiveDb | SsdtProject | DacpacFile | RawSql`; ships when operator demand for ad-hoc schema-diff outside the canary's specific source-vs-deployed-target scope materializes.")>]
let ``5.7.α row 109: V1 dmm-compare verb sunsets — V2 canary subsumes; future projection compare reserved at row 41`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 109"

[<Fact(Skip = "Matrix row 110 — 🟡 DIVERGENCE. V1's `Osm.Cli/Commands/InspectCommandFactory.cs` (inspect verb) consumes V1 JSON model file → model summary (module/entity/attribute counts). V2 omits dedicated inspect verb at launch — surfaces model validation via config-validation errors at emit time (exit code 6 + diagnostic output). **Rationale**: V2 assumes models are pre-validated by the config (Config carries model path; V2 validates file existence + parseability at emit time). **Cash-out**: `osm validate <model.json>` or `osm validate --config <path>` verb — wraps config validation + model ingestion; reuses existing validation machinery; ~30 LOC. **Trigger**: operators demand pre-flight validation separate from full emit (e.g., model-file health checks in CI).")>]
let ``5.7.α row 110: V1 inspect verb vs V2 emit-time validation (V2 surfaces via config errors)`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 110"

[<Fact(Skip = "Matrix row 111 — 🟠 NOT-MAPPED. V1's `Osm.Cli/Commands/AnalyzeCommandFactory.cs` (analyze verb) consumes V1 JSON model + profile snapshot → tightening analysis report (columns / indexes / FKs to tighten + remediation summary). V2's tightening decisions are embedded in the pipeline; analysis output (decision log + manifest) writes at emit time. **Cash-out shape**: `osm analyze <model.json> [--profile <path>] [--policy <path>] --out <report-dir>` — wraps PassDriver + decision-log writer; emits the three DecisionSet outputs + diagnostics + manifest WITHOUT emitting the SSDT artifacts. Reuses NullabilityRules/UniqueIndexRules/ForeignKeyRules unchanged. ~300 LOC. **Dependencies**: SummaryFormatter consumer (row 81 cash-out) for operator-friendly bucket prose. **Trigger**: operators iterate on tightening policy before emission (typical pre-cutover workflow); chapter 5.1.δ window.")>]
let ``5.7.α row 111: V1 analyze verb lifts to V2 osm analyze (analysis-only without SSDT emission)`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 111"

[<Fact(Skip = "Matrix row 112 — 🟠 NOT-MAPPED. V1's `Osm.Cli/Commands/PolicyCommandFactory.cs` carries the `policy explain` subcommand: consumes policy decision report JSON + filter flags → formatted report (table or JSON) with decision rollups + diagnostics. V2's policy surface is emit-time decision log + manifest; post-analysis inspection deferred to external tooling. **Cash-out shape**: lightweight `osm policy explain <decision-log.json> [--axis nullability|fk|unique] [--format table|json]` verb — wraps PolicyDecisionReport deserialization + TableFormatter (reuses V1's PolicyCommandFactory.EmitTableOutput pattern as reference); ~300 LOC. **Trigger**: operators request CLI-based policy drill-down (typical for cutover dry-run reviews). Belongs alongside the SummaryFormatter consumer (row 81 cash-out).")>]
let ``5.7.α row 112: V1 policy explain subcommand lifts to V2 osm policy explain on decision-log artifacts`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 112"

[<Fact(Skip = "Matrix row 113 — 🟠 NOT-MAPPED. V1's `Osm.Cli/Commands/UatUsersCommand.cs` + `UatUsersCommandFactory.cs` (uat-users verb) consumes V1 JSON model + QA/UAT inventory CSVs + user-matching config → UAT user-remapping artifacts (SQL scripts; verification report). Domain-specific orchestration for multi-environment cutover user-identity management. V2 defers to post-deploy phase. Core capability (user-matching strategies; FK remapping) IS V2-portable — chapter 4.2 (User FK reflow) shipped consumer-side IR via `UserRemap.fs` + `UserFkReflowPass.fs`. **Cash-out shape**: `osm uat-users <model.json> <inventory-config.json> --out <dir>` with pluggable matching strategies; ~1500 LOC (substantial because of CSV ingestion + multi-environment orchestration, but core logic reuses V2's existing UserRemap surface). **Trigger**: chapter 4.2 (consumer-side reflow already shipped) + cutover enters UAT phase. Paired with V2's chapter 4.2 + chapter 4.3 deliverables.")>]
let ``5.7.α row 113: V1 uat-users verb lifts to V2 osm uat-users orchestrating chapter 4.2 UserFkReflow consumer side`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 113"

[<Fact(Skip = "Matrix row 114 — 🟠 NOT-MAPPED. V1's `Osm.Cli/Commands/VerifyDataCommandFactory.cs` (verify-data verb) consumes V1 JSON model + source DB connection + target DB connection → data integrity verification report (row-count, NULL-count, warning summaries). Operational assurance run after deployment to confirm data fidelity. V2's canary (matrix row 44) covers **structural equivalence** (schema shape, counts); post-deploy **data integrity** is a separate operational phase. **Cash-out shape**: `osm verify-data <source-conn> <target-conn> <manifest-path> --report-out <path>` — wraps a `BasicDataIntegrityChecker` adapter (port of V1's logic); compares per-table row-counts + per-column null-counts; emits operator report. ~200 LOC. **Dependencies**: row 85 (LiveProfiler adapter) for the per-column probe machinery. **Trigger**: chapter 4.3+ (post-deploy verification phase).")>]
let ``5.7.α row 114: V1 verify-data verb lifts to V2 osm verify-data on post-deploy data integrity check`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 114"

[<Fact(Skip = "Matrix row 115 — 🟠 NOT-MAPPED. V1's `Osm.Cli/Commands/OpenReportVerbExtension.cs` + `PipelineReportLauncher.cs` provide `--open-report` extension on build-ssdt + full-export verbs; uses ShellExecute to open SSMS / Excel with the .dacpac context. V2 omits this — operator workflow is `osm emit --config <path> && osm deploy <manifest>` (sequential) + manual report inspection. **Cash-out shape**: inline `--open-report` option on `osm deploy <manifest> --open-report` (wraps V1's PipelineReportLauncher pattern); ~150 LOC. No dedicated verb. **Trigger**: operators demand integrated report-launching at deploy-time. **Dependencies**: ShellExecute is OS-specific — V2 needs a cross-platform shim (`xdg-open` on Linux; `open` on macOS; `start` on Windows). Reasonable to ship; not blocking cutover.")>]
let ``5.7.α row 115: V1 --open-report extension lifts to V2 osm deploy --open-report flag (cross-platform shim)`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 115"

[<Fact(Skip = "Matrix row 116 — 🟡 DIVERGENCE. V1's option-binding architecture: 7 specialized binders (`ModuleFilterOptionBinder`, `CacheOptionBinder`, `SqlOptionBinder`, `TighteningOptionBinder`, `SchemaApplyOptionBinder`, `UatUsersOptionBinder`, `IVerbOptionExtension`) + `VerbOptionRegistry` + `VerbOptionsBuilder` — verbs chain via `.UseModuleFilter().UseSql().UseTightening()` composable + extensible. V2's `Projection.Cli/Program.fs` uses raw `argv` pattern matching (main argv switch). V2's posture: defer complex binding to config files (Config carries model path, table renames, etc.); CLI takes essential switches only. **Trade-off**: V1's CLI is more powerful; V2's is simpler + config-secondary. **Re-open trigger**: future CLI expansion demands strongly-typed composition (e.g., `osm emit --with-cache --with-module-filter --with-tightening`); cash-out: carbon-copy V1's binder patterns to F# (~500 LOC port of `ModuleFilterOptionBinder` + `VerbOptionsBuilder` + per-axis binders). Reasonable if V2's CLI surface expands beyond 4 verbs.")>]
let ``5.7.α row 116: V1 7-binder option-binding registry vs V2 raw argv pattern matching (V2 minimal)`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 116"

[<Fact(Skip = "Matrix row 117 — 🟡 DIVERGENCE. V1's `Osm.Cli/CliGlobalOptions.cs` carries cross-verb config (config path; max parallelism; etc.); dependency-injected into every verb factory. V2 has no global options at launch — argv switch per-verb; CLI flags only override config defaults. **Rationale**: V2 is config-driven (unified config JSON carries cross-verb defaults; CLI flags are per-invocation overrides only). **Re-open trigger**: operators need CLI-level global flags (`--log-level`, `--verbose`, `--quiet`); cash-out: add `CliGlobalOptions` record to V2's Program.fs; parse before verb dispatch; thread into each verb's runner. ~50 LOC.")>]
let ``5.7.α row 117: V1 CliGlobalOptions DI vs V2 config-driven (no global options at launch)`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 117"

[<Fact(Skip = "Matrix row 118 — 🟠 NOT-MAPPED. V1's `Osm.Cli/IProgressRunner.cs` + `SpectreConsoleProgressService.cs` integrate Spectre.Console TUI library — wraps every verb run in a progress bar (task descriptions, % complete, ETA). V2 has no progress surface at launch. **Cash-out shape**: hook V2's existing `Projection.Core/Bench.fs` iterator-logging primitives (per-iteration samples already emitted; matrix row 36 covers the extraction-side analog) into a Spectre.Console renderer at the CLI boundary. `SpectreProgressAdapter : IProgressRunner` wrapping `Bench.snapshot()` samples. ~200 LOC. **Dependencies**: paired with matrix row 36 (extraction progress). Per `DECISIONS 2026-05-23 — Iterator-logging is a first-class outcome over time` — V2's Bench surface is already operator-visible; this row adds the TUI rendering. **Trigger**: chapter 5.1 (production CLI wiring) + operator feedback on visibility during long-running operations.")>]
let ``5.7.α row 118: V1 IProgressRunner + Spectre TUI lifts to V2 SpectreProgressAdapter on Bench iterator-samples`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 118"

[<Fact(Skip = "Matrix row 119 — 🟡 DIVERGENCE. V1's `Osm.Cli/CommandConsole.cs` abstraction (Write / WriteErrorLine / WriteTable / WriteErrors) centralizes error formatting. V2's `Projection.Cli/Program.fs` uses direct `Console.Error.WriteLine` per error (structured per-line writes per chapter 3.5 audit — typed list flows in; per-line writes flow out; no intermediate concatenation; pure functional I/O). **V2 is more testable** (output is deterministic; no formatting class to mock). Both approaches sound; **deliberate choice** — V2's pillar 1 (data-structure-oriented; strings emerge at terminal boundary only). No DECISIONS row needed — covered by chapter 3.5 audit + pillar 1.")>]
let ``5.7.α row 119: V1 CommandConsole abstraction vs V2 per-line BCL writes (V2 testable + per pillar 1)`` () : unit =
    failwith "deferred — see V1_PARITY_MATRIX.md row 119"

[<Fact>]
let ``5.7.α.cli: cli-verbs parity file present`` () =
    Assert.True(true)
