#!/usr/bin/env bash
#
# matrix-status.sh — EXECUTION_PLAN slice E2 (seed); makes NORTH_STAR.md §1
# self-reporting (NORTH_STAR criterion 5, documentation totality / T-IV).
#
# Derives, from the code, two things and writes them to NORTH_STAR.matrix.generated.md:
#   1. The L2 executable-axiom rollup + the T-II gate verdict, machine-derived from
#      tests/Projection.Tests/AxiomTests.fs (live verified/convention vs deferred C/D).
#   2. The §1 round-trip matrix, where each cell names a witness test and the generator
#      VERIFIES that a test by that name exists in the tree — a cell asserted green whose
#      witness is absent renders OPEN (the generator under-claims; it never over-claims).
#
# Honesty mechanism: a human cannot mark a cell green; the witness test must exist.
# As Waves 1-4 land their witness tests, cells flip automatically on regeneration.
# Run at chapter close; a non-empty `git diff` on the generated file = a coverage shift.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
AX="$ROOT/tests/Projection.Tests/AxiomTests.fs"
TESTS="$ROOT/tests"
OUT="$ROOT/NORTH_STAR.matrix.generated.md"
[ -f "$AX" ] || { echo "matrix-status: AxiomTests.fs not found" >&2; exit 2; }

skips="$(grep -E '\[<Fact\(Skip' "$AX" || true)"
live=$(grep -cE '^[[:space:]]*\[<Fact>\]' "$AX" || true)
skip_total=$(printf '%s\n' "$skips" | grep -c . || true)
c=$(printf '%s\n' "$skips" | grep -cE 'Bucket C' || true)
d=$(printf '%s\n' "$skips" | grep -cE 'Bucket D' || true)
total=$(( live + skip_total ))

if "$ROOT/scripts/verifiability-gate.sh" >/dev/null 2>&1; then tii="PASS"; else tii="FAIL"; fi

# Cell declarations: "Axis|Operation|witness-test-substring|EXECUTION_PLAN slice".
# A cell is VERIFIED iff a backtick-quoted test name containing the substring exists
# under tests/ (matches both `let ``...``` and `member _.``...``` declarations).
cells='Schema|round-trip (canary)|PhysicalSchema diff|Wave 1 (1.2/1.3 un-hollow)
Data|round-trip (data canary)|data canary|Transfer (shipped)
Identity|round-trip (SsKey reload)|reload preserves SsKey|Wave 4.1
Time|round-trip (replay)|replayTo genesis|E4 / 5.3
Decision|round-trip (overlay)|reproduces the DecisionOverlay|E3 / Wave 2'

witness_status() {
  local pat="$1"
  if grep -rhE "\`\`[^\`]*${pat}" "$TESTS" >/dev/null 2>&1; then echo "VERIFIED"; else echo "OPEN"; fi
}
icon() { case "$1" in VERIFIED) echo "✅ verified";; *) echo "⬚ open";; esac; }

green=0; counted=0; rows=""
while IFS='|' read -r axis op pat slice; do
  [ -z "$axis" ] && continue
  st=$(witness_status "$pat")
  counted=$((counted+1))
  [ "$st" = "VERIFIED" ] && green=$((green+1))
  rows+="| **$axis** | $op | \`$pat\` | $slice | $(icon "$st") |"$'\n'
done <<< "$cells"

{
  echo "<!-- GENERATED by scripts/matrix-status.sh — DO NOT EDIT BY HAND."
  echo "     A non-empty git diff on this file at chapter close = a coverage shift."
  echo "     Regenerate: ./scripts/matrix-status.sh -->"
  echo
  echo "# NORTH STAR — Matrix Status (generated)"
  echo
  echo "_Derived from \`tests/Projection.Tests/AxiomTests.fs\` + the test tree. The §1 bullseye, self-reported._"
  echo
  echo "## T-II — Executable-axiom totality (L2 formal axioms)"
  echo
  echo "| Class | Meaning | Count |"
  echo "|---|---|---:|"
  echo "| Live | verified (\"verified by …\") or convention-enforced \`[<Fact>]\` | $live |"
  echo "| Deferred C | weakness — \`[<Fact(Skip … Bucket C …)>]\` | $c |"
  echo "| Deferred D | unnamed/unbacked — \`[<Fact(Skip … Bucket D …)>]\` | $d |"
  echo "| **total axiom entries** | | **$total** |"
  echo
  echo "**Verifiability gate (E1): \`$tii\`** — no deferral claims verified (no phantom Bucket-A/B); every deferral names its bucket."
  echo
  echo "## T-I — Round-trip totality (the §1 bullseye matrix)"
  echo
  echo "| Axis | Operation | Witness test (must exist) | Path | Status |"
  echo "|---|---|---|---|---|"
  printf '%s' "$rows"
  echo
  echo "**Round-trip cells with a live witness: $green / $counted.** A cell goes green only when a test"
  echo "by its witness name exists in the tree — it cannot be asserted by hand. \`⬚ open\` cells are the"
  echo "remaining bullseye distance; they flip automatically as the named slices land their witnesses."
  echo
  echo "> **Witness-present ≠ feature-complete.** This generated view proves a round-trip *witness exists*."
  echo "> Per-feature totality (e.g. the Schema canary is still hollow for triggers/sequences/defaults/"
  echo "> computed/checks/ext-props until Wave 1) lives in NORTH_STAR.md §1 prose; the full E2 generator"
  echo "> will track per-feature. Today this is the coarse, honest, machine-derived floor."
  echo
  echo "_Generated $(date -u +%Y-%m-%dT%H:%MZ) · gate=$tii · L2 live/C/D=${live}/${c}/${d} · round-trip=${green}/${counted}_"
} > "$OUT"

echo "matrix-status: wrote $OUT (gate=$tii; L2 live/C/D=${live}/${c}/${d}; round-trip ${green}/${counted})"
