#!/usr/bin/env python3
"""Package the ssdt-agent tree as Claude Code skills/agents — apply | check.

CONNECTORS.md §1, executed with the repo's regenerate-and-diff discipline
instead of raw copies: each packaged entry is a POINTER SKILL — the source
SKILL.md's frontmatter verbatim (the `description` is the dispatch surface
Claude Code triggers on) plus a one-line body that routes to the canonical
in-tree file. One canonical body, working relative citations, no drift
surface beyond the frontmatter — and the `packaging` gate
(ssdt-agent-gates.py) fails CI whenever source and package disagree.

  apply   (re)generate .claude/skills/<name>/SKILL.md for every
          ssdt-agent/skills/**/SKILL.md, and .claude/agents/<name>.md for
          every ssdt-agent/agents/*.md
  check   exit 1 if the packaged set is missing, stale, or orphaned

`skills/operations/*.md` are knowledge files, not skills, and are never
packaged (CONNECTORS.md §1's explicit carve-out).
"""

import os
import re
import sys
import glob

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(PROJ))
TREE = os.path.join(PROJ, "ssdt-agent")
DOT = os.path.join(REPO, ".claude")

FRONT = re.compile(r"\A---\n(.*?\n)---\n", re.S)


def sources():
    for p in sorted(glob.glob(os.path.join(TREE, "skills", "**", "SKILL.md"), recursive=True)):
        rel = os.path.relpath(p, REPO)
        name = os.path.basename(os.path.dirname(p))
        yield "skill", name, p, rel
    for p in sorted(glob.glob(os.path.join(TREE, "agents", "*.md"))):
        rel = os.path.relpath(p, REPO)
        name = os.path.splitext(os.path.basename(p))[0]
        yield "agent", name, p, rel


def frontmatter(path):
    m = FRONT.match(open(path, encoding="utf-8").read())
    if not m:
        raise SystemExit(f"no frontmatter in {path}")
    return m.group(1)


def rendered(kind, name, src, rel):
    fm = frontmatter(src)
    if kind == "skill":
        body = (f"The canonical skill body lives in the tree, where its relative citations resolve:\n"
                f"**Read `{rel}` now and follow it exactly.** This package is the dispatch pointer\n"
                f"(generated by `sidecar/projection/scripts/ssdt-agent-package.py apply`; do not edit by hand).\n")
    else:
        body = (f"Adopt the role defined at `{rel}` — **Read that file now and follow it exactly**,\n"
                f"then proceed with the task you were given. This package is the dispatch pointer\n"
                f"(generated by `sidecar/projection/scripts/ssdt-agent-package.py apply`; do not edit by hand).\n")
    return f"---\n{fm}---\n\n{body}"


def target(kind, name):
    if kind == "skill":
        return os.path.join(DOT, "skills", name, "SKILL.md")
    return os.path.join(DOT, "agents", name + ".md")


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "check"
    expected = {}
    for kind, name, src, rel in sources():
        expected[target(kind, name)] = rendered(kind, name, src, rel)

    if mode == "apply":
        for t, content in expected.items():
            os.makedirs(os.path.dirname(t), exist_ok=True)
            with open(t, "w", encoding="utf-8") as f:
                f.write(content)
        print(f"packaged {len(expected)} entries into .claude/")
        return

    problems = []
    for t, content in expected.items():
        if not os.path.exists(t):
            problems.append(f"missing package: {os.path.relpath(t, REPO)}")
        elif open(t, encoding="utf-8").read() != content:
            problems.append(f"stale package (re-run `ssdt-agent-package.py apply`): {os.path.relpath(t, REPO)}")
    marker = "ssdt-agent-package.py apply"
    for t in glob.glob(os.path.join(DOT, "skills", "*", "SKILL.md")) + glob.glob(os.path.join(DOT, "agents", "*.md")):
        if t not in expected and marker in open(t, encoding="utf-8").read():
            problems.append(f"orphan package (source gone): {os.path.relpath(t, REPO)}")
    if problems:
        print(f"ssdt-agent packaging: {len(problems)} problem(s)")
        for p in problems:
            print(f"  {p}")
        sys.exit(1)
    print(f"ssdt-agent packaging: {len(expected)} entries in sync")


if __name__ == "__main__":
    main()
