/* ============================================================================
   Static Seeds — generated by the projection engine.
   Idempotent upserts, one block per entity, in FK-safe order.
   ============================================================================ */

SET NOCOUNT ON;
GO

-- ============================================================================
-- Static Seeds: Statics
-- ============================================================================

-- Country (3 rows)
MERGE INTO [dbo].[Country]
 AS [Target]
USING
(
    VALUES
        (N'CA', 2, N'Canada'),
        (N'MX', 3, N'Mexico'),
        (N'US', 1, N'United States')
) AS [Source]([Code], [Id], [Label]) ON [Target].[Id] = [Source].[Id]
WHEN MATCHED THEN UPDATE 
    SET [Target].[Code]  = [Source].[Code],
        [Target].[Label] = [Source].[Label]
WHEN NOT MATCHED THEN INSERT ([Code], [Id], [Label]) VALUES ([Source].[Code], [Source].[Id], [Source].[Label]);
GO
-- RegionA (1 row)
MERGE INTO [dbo].[RegionA]
 AS [Target]
USING
(
    VALUES
        (1, N'North', 1)
) AS [Source]([Id], [Name], [PartnerId]) ON [Target].[Id] = [Source].[Id]
WHEN MATCHED THEN UPDATE 
    SET [Target].[Name]      = [Source].[Name],
        [Target].[PartnerId] = [Source].[PartnerId]
WHEN NOT MATCHED THEN INSERT ([Id], [Name], [PartnerId]) VALUES ([Source].[Id], [Source].[Name], [Source].[PartnerId]);
GO
-- RegionB (1 row)
MERGE INTO [dbo].[RegionB]
 AS [Target]
USING
(
    VALUES
        (1, N'South', 1)
) AS [Source]([Id], [Name], [PartnerId]) ON [Target].[Id] = [Source].[Id]
WHEN MATCHED THEN UPDATE 
    SET [Target].[Name]      = [Source].[Name],
        [Target].[PartnerId] = [Source].[PartnerId]
WHEN NOT MATCHED THEN INSERT ([Id], [Name], [PartnerId]) VALUES ([Source].[Id], [Source].[Name], [Source].[PartnerId]);
GO
-- ScopedLookup (2 rows)
MERGE INTO [dbo].[ScopedLookup]
 AS [Target]
USING
(
    VALUES
        (1, 42, N'Alpha'),
        (2, 42, N'Beta')
) AS [Source]([Id], [TenantId], [Value]) ON [Target].[Id] = [Source].[Id]
WHEN MATCHED THEN UPDATE 
    SET [Target].[TenantId] = [Source].[TenantId],
        [Target].[Value]    = [Source].[Value]
WHEN NOT MATCHED THEN INSERT ([Id], [TenantId], [Value]) VALUES ([Source].[Id], [Source].[TenantId], [Source].[Value])
WHEN NOT MATCHED BY SOURCE AND [Target].[TenantId] = 42 THEN DELETE;
GO
-- TextFidelity (4 rows)
MERGE INTO [dbo].[TextFidelity]
 AS [Target]
USING
(
    VALUES
        (N'', 1),
        (NULL, 2),
        (NULL, 3),
        (N'hello', 4)
) AS [Source]([Body], [Id]) ON [Target].[Id] = [Source].[Id]
WHEN MATCHED THEN UPDATE 
    SET [Target].[Body] = [Source].[Body]
WHEN NOT MATCHED THEN INSERT ([Body], [Id]) VALUES ([Source].[Body], [Source].[Id]);
GO
-- Tier (3 rows)
SET IDENTITY_INSERT [dbo].[Tier] ON;
MERGE INTO [dbo].[Tier]
 AS [Target]
USING
(
    VALUES
        (1, N'Bronze'),
        (3, N'Gold'),
        (2, N'Silver')
) AS [Source]([Id], [Name]) ON [Target].[Id] = [Source].[Id]
WHEN MATCHED THEN UPDATE 
    SET [Target].[Name] = [Source].[Name]
WHEN NOT MATCHED THEN INSERT ([Id], [Name]) VALUES ([Source].[Id], [Source].[Name]);
SET IDENTITY_INSERT [dbo].[Tier] OFF;
GO
