-- Generated by sidecar/projection/scripts/ssdt-agent-package.mjs estate-kit-apply (ssdt-agent-package). Do not edit by hand; edit scripts/estate-kit/ and re-run.
CREATE TABLE [dbo].[Customer] (
    [Id]       INT            IDENTITY(1,1) NOT NULL,
    [Name]     NVARCHAR(100)  NOT NULL,
    [Email]    NVARCHAR(250)  NULL,
    [StatusId] INT            NOT NULL,
    [RegionId] INT            NULL,
    [Score]    INT            NULL,
    CONSTRAINT [PK_Customer] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_Customer_Status] FOREIGN KEY ([StatusId]) REFERENCES [dbo].[Status] ([Id])
);
