-- Generated by sidecar/projection/scripts/ssdt-agent-package.mjs estate-kit-apply (ssdt-agent-package). Do not edit by hand; edit scripts/estate-kit/ and re-run.
CREATE TABLE [dbo].[Region] (
    [Id]   INT           NOT NULL,
    [Name] NVARCHAR(50)  NOT NULL,
    CONSTRAINT [PK_Region] PRIMARY KEY ([Id])
);
