/* ==========================================================================
   Static Entity Seed Script
   Generated by OutSystems DDL Exporter
   This script merges reference data captured from static entities so that
   SSDT deployments remain idempotent across environments.
   --------------------------------------------------------------------------
   The blocks below are populated at generation time. Each block issues a
   MERGE statement scoped to a specific static entity.
   ==========================================================================
*/

SET NOCOUNT ON;

--------------------------------------------------------------------------------
-- Module: AppCore
-- Entity: City (dbo.OSUSR_DEF_CITY)
-- Target: dbo.City
--------------------------------------------------------------------------------
MERGE INTO [dbo].[City] AS Target
USING
(
    VALUES
        (1, N'Lisbon', 1),
        (2, N'Porto', 1),
        (3, N'Madrid', 0)
) AS Source ([ID], [NAME], [ISACTIVE])
    ON Target.[ID] = Source.[ID]
WHEN MATCHED THEN UPDATE SET
    Target.[NAME] = Source.[NAME],
    Target.[ISACTIVE] = Source.[ISACTIVE]
WHEN NOT MATCHED THEN INSERT ([ID], [NAME], [ISACTIVE])
    VALUES (Source.[ID], Source.[NAME], Source.[ISACTIVE]);

GO

