/* ==========================================================================
   Static Entity Seed Script
   Generated by OutSystems DDL Exporter
   This script merges reference data captured from static entities so that
   SSDT deployments remain idempotent across environments.
   --------------------------------------------------------------------------
   The blocks below are populated at generation time. Each block issues a
   MERGE statement scoped to a specific static entity.
   ==========================================================================
*/

SET NOCOUNT ON;

--------------------------------------------------------------------------------
-- Module: AppCore
-- Entity: City (dbo.OSUSR_DEF_CITY)
-- Target: dbo.City
--------------------------------------------------------------------------------
SET IDENTITY_INSERT [dbo].[City] ON;
GO

MERGE INTO [dbo].[City] AS Target
USING
(
    VALUES
        (1, N'Lisbon', 1),
        (2, N'Porto', 1),
        (3, N'Madrid', 0)
) AS Source ([Id], [Name], [IsActive])
    ON Target.[Id] = Source.[Id]
WHEN MATCHED THEN UPDATE SET
    Target.[Name] = Source.[Name],
    Target.[IsActive] = Source.[IsActive]
WHEN NOT MATCHED THEN INSERT ([Id], [Name], [IsActive])
    VALUES (Source.[Id], Source.[Name], Source.[IsActive]);

GO

SET IDENTITY_INSERT [dbo].[City] OFF;
GO

