-- Generated by sidecar/projection/scripts/ssdt-agent-package.mjs estate-kit-apply (ssdt-agent-package). Do not edit by hand; edit scripts/estate-kit/ and re-run.
-- PRE-AUTHORED PROOF EDIT — reference add (copy over Modules/dbo.Customer.sql).
-- RegionId gains its constraint over rows that ALL point at real parents:
-- the publish applies, and the trust probe must then read is_not_trusted = 0
-- (the engine re-validated the existing rows as the constraint went on). A
-- machine whose engine reads 1 does NOT re-validate — record it in the
-- toolchain ledger and add the WITH CHECK CHECK re-validation step to the
-- reference records on that machine.
CREATE TABLE [dbo].[Customer] (
    [Id]       INT            IDENTITY(1,1) NOT NULL,
    [Name]     NVARCHAR(100)  NOT NULL,
    [Email]    NVARCHAR(250)  NULL,
    [StatusId] INT            NOT NULL,
    [RegionId] INT            NULL,
    [Score]    INT            NULL,
    CONSTRAINT [PK_Customer] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_Customer_Status] FOREIGN KEY ([StatusId]) REFERENCES [dbo].[Status] ([Id]),
    CONSTRAINT [FK_Customer_Region] FOREIGN KEY ([RegionId]) REFERENCES [dbo].[Region] ([Id])
);
