/* ==========================================================================
   Static Entity Seed Script
   Generated by OutSystems DDL Exporter
   This script merges reference data captured from static entities so that
   SSDT deployments remain idempotent across environments.
   --------------------------------------------------------------------------
   The blocks below are populated at generation time. Each block issues a
   MERGE statement scoped to a specific static entity.
   ==========================================================================
*/

SET NOCOUNT ON;

--------------------------------------------------------------------------------
-- Module: Matrix
-- Entity: TemporalOrder (dbo.OSUSR_M_TEMPORALORDER)
-- Target: dbo.TemporalOrder
--------------------------------------------------------------------------------
MERGE INTO [dbo].[TemporalOrder] AS Target
USING
(
    VALUES
        (1, N'PENDING', 1, CAST('2025-01-01 00:00:00.0000000' AS datetime2(7)), CAST('9999-12-31 23:59:59.0000000' AS datetime2(7)))
) AS Source ([Id], [Status], [AuditId], [ValidFrom], [ValidTo])
    ON Target.[Id] = Source.[Id]
WHEN MATCHED THEN UPDATE SET
    Target.[Status] = Source.[Status],
    Target.[AuditId] = Source.[AuditId],
    Target.[ValidFrom] = Source.[ValidFrom],
    Target.[ValidTo] = Source.[ValidTo]
WHEN NOT MATCHED THEN INSERT ([Id], [Status], [AuditId], [ValidFrom], [ValidTo])
    VALUES (Source.[Id], Source.[Status], Source.[AuditId], Source.[ValidFrom], Source.[ValidTo])
;

GO


