#!/usr/bin/env bash
# LAWS.md from the tests (V3_INSTRUCTION_ARCHITECTURE.md section 6.10, VALUES.md L6): one row per test method carrying a
# [Trait("Law", "<the law>")], with the law, the method's name in English and its full name (namespace, class, method), sorted
# by law and then by full name, the generated banner first and no timestamp; whether each is green is the CI run's to say.
# ci/laws.ps1 takes the same steps and writes the same bytes. Usage: ci/laws.sh [output], LAWS.md at the root by default.
set -euo pipefail
export LC_ALL=C

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="${1:-$root/LAWS.md}"

rows="$(cd "$root" && find tests -name '*.cs' -not -path 'tests/Golden/*' -not -path '*/bin/*' -not -path '*/obj/*' | sort | while IFS= read -r file; do
  awk '
    { sub(/\r$/, "") }
    match($0, /^namespace [A-Za-z0-9_.]+;/) { space = substr($0, 11, RLENGTH - 11) }
    match($0, /^[ \t]*((public|internal|private|sealed|static|abstract|partial|file)[ \t]+)*class[ \t]+[A-Za-z0-9_]+/) {
      declared = substr($0, RSTART, RLENGTH); sub(/.*class[ \t]+/, "", declared); type = declared
    }
    match($0, /\[Trait\("Law", "[^"]+"\)\]/) { laws[++pending] = substr($0, RSTART + 15, RLENGTH - 18) }
    pending > 0 && match($0, /^[ \t]*public (async )?[A-Za-z0-9_<>]+ [A-Za-z0-9_]+\(/) {
      method = substr($0, RSTART, RLENGTH - 1); sub(/.* /, "", method)
      english = method; gsub(/_s_/, "'\''s_", english); gsub(/_/, " ", english)
      for (i = 1; i <= pending; i++) printf "%s\t%s.%s.%s\t%s\n", laws[i], space, type, method, english
      pending = 0
    }
  ' "$file"
done | sort)"

{
  printf '%s\n' '<!-- generated by ci/laws.sh, or ci/laws.ps1 on Windows, from the tests'"'"' Law traits; do not edit -->'
  printf '%s\n' '# Laws' ''
  printf '%s\n' 'One row per test that states a law, from its `[Trait("Law", …)]`: the law, the test'"'"'s name in English, and its full name.'
  printf '%s\n' 'Whether each is green is the CI run'"'"'s to say. A law without a green test is not a law.' ''
  printf '%s\n' '| Law | The test, in English | The test |' '|---|---|---|'
  if [ -n "$rows" ]; then
    printf '%s\n' "$rows" | awk -F '\t' '{ printf "| %s | %s | `%s` |\n", $1, $3, $2 }'
  fi
} > "$out"
