# LAWS.md from the tests, as ci/laws.sh writes it, byte for byte: one row per test method carrying a [Trait("Law", "<the law>")],
# with the law, the method's name in English and its full name, sorted ordinally by law and then by full name, the generated
# banner first and no timestamp. Usage: ci/laws.ps1 [output], LAWS.md at the root by default.
param([string]$Output)
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
if (-not $Output) { $Output = Join-Path $root 'LAWS.md' }

$files = Get-ChildItem -Path (Join-Path $root 'tests') -Recurse -File -Filter '*.cs' |
  ForEach-Object { [IO.Path]::GetRelativePath($root, $_.FullName).Replace('\', '/') } |
  Where-Object { $_ -notlike 'tests/Golden/*' -and $_ -notmatch '/(bin|obj)/' }
$files = [string[]]@($files); [Array]::Sort($files, [StringComparer]::Ordinal)

$rows = [Collections.Generic.List[string]]::new()
foreach ($file in $files) {
  $space = ''; $type = ''; $laws = [Collections.Generic.List[string]]::new()
  foreach ($line in [IO.File]::ReadAllLines((Join-Path $root $file), [Text.UTF8Encoding]::new($false))) {
    if ($line -cmatch '^namespace ([A-Za-z0-9_.]+);') { $space = $Matches[1] }
    if ($line -cmatch '^[ \t]*((public|internal|private|sealed|static|abstract|partial|file)[ \t]+)*class[ \t]+([A-Za-z0-9_]+)') { $type = $Matches[3] }
    if ($line -cmatch '\[Trait\("Law", "([^"]+)"\)\]') { $laws.Add($Matches[1]) }
    if ($laws.Count -gt 0 -and $line -cmatch '^[ \t]*public (async )?[A-Za-z0-9_<>]+ ([A-Za-z0-9_]+)\(') {
      $method = $Matches[2]
      $english = ($method -creplace '_s_', "'s_") -creplace '_', ' '
      foreach ($law in $laws) { $rows.Add("$law`t$space.$type.$method`t$english") }
      $laws.Clear()
    }
  }
}

$sorted = [string[]]$rows.ToArray(); [Array]::Sort($sorted, [StringComparer]::Ordinal)
$text = [Text.StringBuilder]::new()
[void]$text.Append("<!-- generated by ci/laws.sh, or ci/laws.ps1 on Windows, from the tests' Law traits; do not edit -->`n# Laws`n`n")
[void]$text.Append("One row per test that states a law, from its ``[Trait(`"Law`", …)]``: the law, the test's name in English, and its full name.`n")
[void]$text.Append("Whether each is green is the CI run's to say. A law without a green test is not a law.`n`n")
[void]$text.Append("| Law | The test, in English | The test |`n|---|---|---|`n")
foreach ($row in $sorted) {
  $cells = $row.Split("`t")
  [void]$text.Append("| $($cells[0]) | $($cells[2]) | ``$($cells[1])`` |`n")
}
[IO.File]::WriteAllText([IO.Path]::GetFullPath($Output), $text.ToString(), [Text.UTF8Encoding]::new($false))
