#!/usr/bin/env bash
# LAWS.md from the tests (V3_INSTRUCTION_ARCHITECTURE.md section 6.10, VALUES.md L6; DECISIONS.md, 2026-09-25): three tables, one
# row per test method carrying a [Trait("Law", "<the law>")], a [Trait("Value", "<a VALUES.md row>")] or a
# [Trait("Exit", "M<n>.<k>")], with the trait's value, the method's name in English and its full name (namespace, class, method);
# after the values, the rows of VALUES.md no test declares, and after the exits, the exits of V3_MILESTONES.md no test declares.
# Laws sort by law and then by full name; values by the row's letter, then its number as a number, then the full name; exits by
# milestone, then exit, then the full name. The generated banner comes first and no timestamp; whether each test is green is the
# CI run's to say. ci/laws.ps1 takes the same steps and writes the same bytes. Usage: ci/laws.sh [output], LAWS.md at the root by default.
set -euo pipefail
export LC_ALL=C

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="${1:-$root/LAWS.md}"
cd "$root"

# Each row: the trait's name, its sort key, its value, the test's full name and its English name, tab-separated, sorted ordinally.
# A comment line is skipped; a class is the last one declared at the start of a line, since a nested helper class, indented, never holds a test.
rows="$(find tests -name '*.cs' -not -path 'tests/Golden/*' -not -path '*/bin/*' -not -path '*/obj/*' | sort | while IFS= read -r file; do
  awk '
    { sub(/\r$/, "") }
    /^[ \t]*\/\// { next }
    match($0, /^namespace [A-Za-z0-9_.]+;/) { space = substr($0, 11, RLENGTH - 11) }
    match($0, /^((public|internal|private|sealed|static|abstract|partial|file)[ \t]+)*class[ \t]+[A-Za-z0-9_]+/) {
      declared = substr($0, RSTART, RLENGTH); sub(/.*class[ \t]+/, "", declared); type = declared
    }
    match($0, /\[Trait\("(Law|Value|Exit)", "[^"]+"\)\]/) {
      trait = substr($0, RSTART + 8, RLENGTH - 11); kind = trait; sub(/".*/, "", kind); value = trait; sub(/^[A-Za-z]+", "/, "", value)
      if (kind == "Value") { key = substr(value, 1, 1) sprintf("%03d", substr(value, 2) + 0) }
      else if (kind == "Exit") { key = sprintf("%02d.%02d", substr(value, 2, index(value, ".") - 2) + 0, substr(value, index(value, ".") + 1) + 0) }
      else { key = value }
      kinds[++pending] = kind; keys[pending] = key; values[pending] = value
    }
    pending > 0 && match($0, /^[ \t]*public (async )?[A-Za-z0-9_<>.]+ [A-Za-z0-9_]+\(/) {
      method = substr($0, RSTART, RLENGTH - 1); sub(/.* /, "", method)
      english = method; gsub(/_s_/, "'\''s_", english); gsub(/_/, " ", english)
      for (i = 1; i <= pending; i++) printf "%s\t%s\t%s\t%s.%s.%s\t%s\n", kinds[i], keys[i], values[i], space, type, method, english
      pending = 0
    }
  ' "$file"
done | sort)"

# The rows of VALUES.md (| S2 | …) no Value trait names, by letter and then number.
undeclared_values="$(awk -F '\t' '
  NR == FNR { if ($1 == "Value") { declared[$3] = 1 }; next }
  { sub(/\r$/, "") }
  match($0, /^\| [A-Z][0-9]+ \|/) { id = substr($0, 3, RLENGTH - 4); if (!(id in declared)) { printf "%s%03d\t%s\n", substr(id, 1, 1), substr(id, 2) + 0, id } }
' <(printf '%s\n' "$rows") VALUES.md | sort | awk -F '\t' '{ s = s (NR > 1 ? ", " : "") $2 } END { print s }')"

# The exits of V3_MILESTONES.md no Exit trait names: the numbered list after **Exit.** in each section headed M<n>, or exit 1 where the exit is a paragraph.
undeclared_exits="$(awk -F '\t' '
  NR == FNR { if ($1 == "Exit") { declared[$3] = 1 }; next }
  { sub(/\r$/, "") }
  match($0, /^## [0-9]+\. M[0-9]/) { m = substr($0, RLENGTH, 1) }
  /^\*\*Exit\.\*\*/ { reading = 1; n = 0; next }
  reading && /^[0-9]+\. / { n++ }
  reading && /^$/ { for (k = 1; k <= (n > 0 ? n : 1); k++) { if (!(("M" m "." k) in declared)) { printf "%02d.%02d\tM%s.%d\n", m, k, m, k } }; reading = 0 }
' <(printf '%s\n' "$rows") V3_MILESTONES.md | sort | awk -F '\t' '{ s = s (NR > 1 ? ", " : "") $2 } END { print s }')"

table() {
  printf '%s\n' "| $2 | The test, in English | The test |" '|---|---|---|'
  if [ -n "$rows" ]; then
    printf '%s\n' "$rows" | awk -F '\t' -v kind="$1" '$1 == kind { printf "| %s | %s | `%s` |\n", $3, $5, $4 }'
  fi
}

{
  printf '%s\n' '<!-- generated by ci/laws.sh, or ci/laws.ps1 on Windows, from the tests'"'"' Law, Value and Exit traits; do not edit -->'
  printf '%s\n' '# Laws' ''
  printf '%s\n' 'One row per test that states a law, from its `[Trait("Law", …)]`: the law, the test'"'"'s name in English, and its full name.'
  printf '%s\n' 'Whether each is green is the CI run'"'"'s to say. A law without a green test is not a law.' ''
  table Law Law
  printf '%s\n' '' '## Values' ''
  printf '%s\n' 'One row per test that holds a row of `VALUES.md`, from its `[Trait("Value", …)]`.' ''
  table Value Value
  printf '%s\n' '' "Rows of \`VALUES.md\` no test declares: ${undeclared_values:-none}."
  printf '%s\n' '' '## Milestone exits' ''
  printf '%s\n' 'One row per test that runs an exit of `V3_MILESTONES.md`, from its `[Trait("Exit", …)]`, as M<n>.<k>.' ''
  table Exit Exit
  printf '%s\n' '' "Exits no test declares, which a person or a CI job runs: ${undeclared_exits:-none}."
} > "$out"
