# Generated by sidecar/projection/scripts/ssdt-agent-package.mjs estate-kit-apply (ssdt-agent-package). Do not edit by hand; edit scripts/estate-kit/ and re-run.
<#
THE ESTATE KIT — reset a proving copy to the pristine template.

    .\reset-proving-copy.ps1 -Name <db> [-Template <path.bak>] [-Templates <dir>]
                             [-Server <engine>] [-SqlUser <u> -SqlPassword <p>]

The contaminated copy is dropped and the template restored again under the
SAME name — the seconds-scale clean slate the proving loop leans on after a
Permissive publish or an adversarial probe dirtied the copy. Restoring is
the reset; there is no repair path.
#>
param(
    [Parameter(Mandatory)] [string] $Name,
    [string] $Template,
    [string] $Templates = '.\templates',
    [string] $Server = '(localdb)\MSSQLLocalDB',
    [string] $SqlUser,
    [string] $SqlPassword
)

$restore = Join-Path $PSScriptRoot 'restore-proving-copy.ps1'
$restoreArgs = @{ Name = $Name; Templates = $Templates; Server = $Server }
if ($Template)    { $restoreArgs.Template = $Template }
if ($SqlUser)     { $restoreArgs.SqlUser = $SqlUser; $restoreArgs.SqlPassword = $SqlPassword }
& $restore @restoreArgs
