#!/usr/bin/env bash
# Generated by sidecar/projection/scripts/ssdt-agent-package.mjs estate-kit-apply (ssdt-agent-package). Do not edit by hand; edit scripts/estate-kit/ and re-run.
# THE ESTATE KIT — stand a proving copy up from the verified template.
#
#   restore-proving-copy.sh [--template <path.bak>] [--name <db>] [--templates <dir>]
#
# Restores the template (default: the newest under --templates, default
# ./templates) into the local container as a disposable copy under the
# PROTOCOL naming (PG_Proving_<8 hex> unless --name overrides), then prints
# the copy's own identity from [twin].[__state] — the restored database
# answers which base it came from; nothing is taken on trust. Container and
# credentials come from KIT_SQL_CONTAINER / KIT_SQL_PASSWORD (defaults in
# kit-common.sh).
set -euo pipefail
. "$(dirname "$0")/kit-common.sh"

TEMPLATE="" NAME="" TEMPLATES_DIR="./templates"
while [ $# -gt 0 ]; do
    case "$1" in
        --template)  TEMPLATE="$2"; shift 2 ;;
        --name)      NAME="$2"; shift 2 ;;
        --templates) TEMPLATES_DIR="$2"; shift 2 ;;
        *) kit_die "unknown argument: $1" ;;
    esac
done

if [ -z "$TEMPLATE" ]; then
    kit_newest_template "$TEMPLATES_DIR"
    TEMPLATE="$KIT_TEMPLATE_BAK"
    kit_verify_template "$KIT_TEMPLATE_BAK" "$KIT_TEMPLATE_MANIFEST"
fi
[ -f "$TEMPLATE" ] || kit_die "no template at $TEMPLATE"
[ -n "$NAME" ] || NAME="PG_Proving_$(openssl rand -hex 4)"

START=$(date +%s%N 2>/dev/null || date +%s)
kit_restore "$TEMPLATE" "$NAME"
END=$(date +%s%N 2>/dev/null || date +%s)
ELAPSED="$(awk -v s="$START" -v e="$END" 'BEGIN { d = e - s; printf (d > 1e6 ? "%.2fs" : "%ds"), (d > 1e6 ? d / 1e9 : d) }')"

kit_log "restored $(basename "$TEMPLATE") as [$NAME] in $ELAPSED"
kit_log "identity: $(kit_identity "$NAME")"
echo "$NAME"
