#!/usr/bin/env bash
# Generated by sidecar/projection/scripts/ssdt-agent-package.mjs estate-kit-apply (ssdt-agent-package). Do not edit by hand; edit scripts/estate-kit/ and re-run.
# THE ESTATE KIT — the one-time machine setup + acceptance suite.
#
#   setup-proving-machine.sh [--templates <dir>] [--skip-template]
#
# Verifies a developer machine end to end before the team leans on it:
#
#   1. Toolchain — dotnet, sqlpackage (against the pinned version this kit
#      was packaged with), the local SQL container, the engine version.
#   2. Template — the newest verified template restores as a disposable
#      copy that answers its own identity, and resets in seconds.
#   3. Acceptance — the known catalog (never the estate's own model)
#      publishes and the engine's verdicts reproduce:
#        - no-op silence: republishing the unchanged model leaves the
#          content digest byte-for-byte identical;
#        - the reference add validates TRUSTED over rows that all point at
#          real parents (is_not_trusted = 0);
#        - the make-mandatory triple: BLOCKED over rows with NULLs, STILL
#          blocked after the NULLs are cleared (the guard is table-has-rows,
#          not column-has-NULLs), and clean only on the emptied table.
#
# Every verdict is read from the engine's PRINTED TEXT, never an exit code.
# The suite ends with the toolchain row to record in estate/toolchain.md.
# Container + credentials come from KIT_SQL_CONTAINER / KIT_SQL_SERVER /
# KIT_SQL_PASSWORD (defaults in kit-common.sh).
set -euo pipefail
KIT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$KIT_DIR/kit-common.sh"

# The sqlpackage pin this kit was PACKAGED with — the packager bakes the
# toolchain ledger's row over the placeholder below. A source-tree run
# (placeholder intact) reports the pin as not yet baked, never silently.
SQLPACKAGE_PIN="UNPINNED"

TEMPLATES_DIR="./templates" SKIP_TEMPLATE=false
while [ $# -gt 0 ]; do
    case "$1" in
        --templates)    TEMPLATES_DIR="$2"; shift 2 ;;
        --skip-template) SKIP_TEMPLATE=true; shift ;;
        *) kit_die "unknown argument: $1" ;;
    esac
done

KIT_FAILURES=0
RAND="$(openssl rand -hex 4)"
ACCEPT_DB="PG_KitAccept_$RAND"
SMOKE_DB="PG_KitSmoke_$RAND"
SCRATCH="${TMPDIR:-/tmp}/estate-kit-accept-$RAND"

cleanup() {
    kit_sql -Q "IF DB_ID(N'$ACCEPT_DB') IS NOT NULL BEGIN ALTER DATABASE [$ACCEPT_DB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE [$ACCEPT_DB]; END; IF DB_ID(N'$SMOKE_DB') IS NOT NULL BEGIN ALTER DATABASE [$SMOKE_DB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE [$SMOKE_DB]; END;" >/dev/null 2>&1 || true
    rm -rf "$SCRATCH"
}
trap cleanup EXIT

# ---------------------------------------------------------------------------
# 1 — toolchain.
# ---------------------------------------------------------------------------
command -v dotnet >/dev/null 2>&1 && kit_pass "dotnet on PATH ($(dotnet --version))" || kit_fail "dotnet is not on PATH"
if command -v sqlpackage >/dev/null 2>&1; then
    SQLPACKAGE_VERSION="$(sqlpackage /version 2>/dev/null | tr -d '\r' | tail -1)"
    case "$SQLPACKAGE_PIN" in
        __SQLPACKAGE_*|UNPINNED)
            kit_pass "sqlpackage on PATH ($SQLPACKAGE_VERSION); the pin is not yet baked — align to the pipeline's DacFx and record both in estate/toolchain.md" ;;
        "$SQLPACKAGE_VERSION")
            kit_pass "sqlpackage $SQLPACKAGE_VERSION matches the kit's pin" ;;
        *)
            kit_fail "sqlpackage $SQLPACKAGE_VERSION differs from the kit's pin $SQLPACKAGE_PIN — trust-state findings are assumed until aligned" ;;
    esac
else
    kit_fail "sqlpackage is not on PATH (dotnet tool install --global microsoft.sqlpackage)"
    SQLPACKAGE_VERSION="(absent)"
fi
if ENGINE="$(kit_scalar -Q "SET NOCOUNT ON; SELECT CONCAT(CAST(SERVERPROPERTY('ProductVersion') AS NVARCHAR(64)), ' · ', CAST(SERVERPROPERTY('Edition') AS NVARCHAR(128)));" 2>/dev/null)" && [ -n "$ENGINE" ]; then
    kit_pass "SQL Server reachable in container '$KIT_CONTAINER' ($ENGINE)"
else
    kit_die "no SQL Server in container '$KIT_CONTAINER' — start the local engine first"
fi

# ---------------------------------------------------------------------------
# 2 — the template: restore, identity, reset.
# ---------------------------------------------------------------------------
if [ "$SKIP_TEMPLATE" = false ]; then
    kit_newest_template "$TEMPLATES_DIR"
    kit_verify_template "$KIT_TEMPLATE_BAK" "$KIT_TEMPLATE_MANIFEST"
    kit_pass "template pair verified ($(basename "$KIT_TEMPLATE_BAK"))"
    kit_restore "$KIT_TEMPLATE_BAK" "$SMOKE_DB"
    IDENTITY="$(kit_identity "$SMOKE_DB")"
    case "$IDENTITY" in
        commit=\(unstamped\)*) kit_fail "the restored copy carries no template identity" ;;
        commit=*)              kit_pass "restored copy answers its identity ($IDENTITY)" ;;
        *)                     kit_fail "the restored copy's identity could not be read" ;;
    esac
    START=$(date +%s)
    kit_restore "$KIT_TEMPLATE_BAK" "$SMOKE_DB"
    kit_pass "reset (drop + restore) in $(( $(date +%s) - START ))s"
else
    kit_log "template smoke skipped (--skip-template)"
fi

# ---------------------------------------------------------------------------
# 3 — the acceptance catalog (a scratch copy; the authored kit is never
# edited — the PROTOCOL discipline).
# ---------------------------------------------------------------------------
mkdir -p "$SCRATCH"
cp -R "$KIT_DIR/acceptance/AcceptanceCatalog/." "$SCRATCH/"
rm -rf "$SCRATCH/bin" "$SCRATCH/obj"

build() { dotnet build "$SCRATCH/AcceptanceCatalog.sqlproj" -c Release >/dev/null 2>&1 || kit_die "the acceptance catalog did not build"; }
publish() {
    # The verdict lives in the TEXT; a blocked publish does not reliably
    # exit non-zero (and a piped one never does).
    sqlpackage /Action:Publish \
        /SourceFile:"$SCRATCH/bin/Release/AcceptanceCatalog.dacpac" \
        /Profile:"$SCRATCH/profiles/Acceptance.Strict.publish.xml" \
        /TargetServerName:"$KIT_SERVER" /TargetDatabaseName:"$ACCEPT_DB" \
        /TargetUser:sa /TargetPassword:"$KIT_PASSWORD" \
        /TargetTrustServerCertificate:True 2>&1 || true
}

build
kit_log "baseline publish (+ seed) to [$ACCEPT_DB]..."
OUT="$(publish)"
printf '%s\n' "$OUT" | grep -q "Successfully published" \
    && kit_pass "baseline catalog published" \
    || { kit_fail "the baseline publish did not succeed"; printf '%s\n' "$OUT" >&2; }

# No-op silence: republish the unchanged model; the digest must not move.
D1="$(kit_digest "$ACCEPT_DB")"
OUT="$(publish)"
D2="$(kit_digest "$ACCEPT_DB")"
if printf '%s\n' "$OUT" | grep -q "Successfully published" && [ "$D1" = "$D2" ]; then
    kit_pass "no-op republish left the content digest unchanged ($D1)"
else
    kit_fail "the no-op republish moved the digest ($D1 -> $D2)"
fi

# The reference add validates TRUSTED over valid rows.
cp -R "$KIT_DIR/acceptance/edits/fk-add/." "$SCRATCH/"
build
OUT="$(publish)"
TRUST="$(kit_scalar -d "$ACCEPT_DB" -Q "SET NOCOUNT ON; SELECT CAST(is_not_trusted AS NVARCHAR(1)) FROM sys.foreign_keys WHERE name = 'FK_Customer_Region';")"
if printf '%s\n' "$OUT" | grep -q "Successfully published" && [ "$TRUST" = "0" ]; then
    kit_pass "reference add validated TRUSTED (is_not_trusted = 0)"
elif [ "$TRUST" = "1" ]; then
    kit_fail "the engine left the added reference UNTRUSTED (is_not_trusted = 1) — record this engine in estate/toolchain.md and add the WITH CHECK CHECK re-validation step to reference records on this machine"
else
    kit_fail "the reference-add publish did not land"; printf '%s\n' "$OUT" >&2
fi

# The make-mandatory triple.
cp -R "$KIT_DIR/acceptance/edits/make-mandatory/." "$SCRATCH/"
build
OUT="$(publish)"
printf '%s\n' "$OUT" | grep -q "Could not deploy package" \
    && kit_pass "make-mandatory BLOCKED over rows with NULLs" \
    || { kit_fail "make-mandatory was not blocked over NULL rows"; printf '%s\n' "$OUT" >&2; }

kit_sql -d "$ACCEPT_DB" -Q "UPDATE [dbo].[Customer] SET [Email] = CONCAT(N'fixed', [Id], N'@acceptance.test') WHERE [Email] IS NULL;" >/dev/null
OUT="$(publish)"
printf '%s\n' "$OUT" | grep -q "Could not deploy package" \
    && kit_pass "make-mandatory STILL blocked after the NULLs were cleared (the guard is table-has-rows)" \
    || { kit_fail "the cleared-NULLs publish was not blocked — the guard read differently on this engine"; printf '%s\n' "$OUT" >&2; }

kit_sql -d "$ACCEPT_DB" -Q "DELETE FROM [dbo].[Customer];" >/dev/null
OUT="$(publish)"
NULLABLE="$(kit_scalar -d "$ACCEPT_DB" -Q "SET NOCOUNT ON; SELECT CAST(COLUMNPROPERTY(OBJECT_ID('dbo.Customer'), 'Email', 'AllowsNull') AS NVARCHAR(1));")"
if printf '%s\n' "$OUT" | grep -q "Successfully published" && [ "$NULLABLE" = "0" ]; then
    kit_pass "make-mandatory publishes clean on the emptied table (Email is NOT NULL)"
else
    kit_fail "the emptied-table publish did not land the NOT NULL"; printf '%s\n' "$OUT" >&2
fi

# ---------------------------------------------------------------------------
# 4 — the verdict, and the ledger row to record.
# ---------------------------------------------------------------------------
echo
if [ "$KIT_FAILURES" -eq 0 ]; then
    kit_log "acceptance complete: every check passed. This machine's proving loop is trustworthy."
else
    kit_log "acceptance complete with $KIT_FAILURES failure(s) — fix the substrate before the team leans on it; do not route around it."
fi
kit_log "record in estate/toolchain.md (per-machine row):"
printf '| machine (%s) | sqlpackage %s · engine %s | this machine | %s | per-machine acceptance %s |\n' \
    "$(hostname)" "$SQLPACKAGE_VERSION" "${ENGINE:-unknown}" "$(date -u +%Y-%m-%d)" \
    "$([ "$KIT_FAILURES" -eq 0 ] && echo PASSED || echo "FAILED ($KIT_FAILURES)")"
exit "$([ "$KIT_FAILURES" -eq 0 ] && echo 0 || echo 1)"
